In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# PADDLE test set proteins (good for creating hits list)

In [ ]:
# Figure 3 source data 
paddle_test_set = pd.read_excel('Paddle_test_set_sequences.xlsx', sheet_name='PADDLE test set predictions')

# Figure 1 source data (1 and 2)
paddle_ads = pd.read_excel("list_of_ADs.xlsx")
paddle_full_seqs = pd.read_excel('screen_data.xlsx', sheet_name='TF sequences, see Fig 1')

In [29]:
# These are full length TFs not used to train PADDLE
paddle_test_set['protein'].value_counts()

protein
OAF1     78
SUM1     78
PIP2     74
ASG1     72
FAP1     72
UPC2     68
RSC30    65
OAF3     64
ARG81    63
RDS1     61
RFX1     60
ECM22    59
TOG1     57
RTG3     35
ACA1     34
MGA1     32
RDS2     31
CUP2     15
RGM1     12
MET32    12
ARG80    11
MET31    11
Name: count, dtype: int64

In [54]:
paddle_test_set[paddle_test_set['protein'] == 'MET31']

,Unnamed: 0,protein sequence,protein,protein ID,position,activation,Z score,predicted activation,predicted Z score
933,A_tiles_Q03081:0,MKLAQDMNVDEIFLKQAAEAIAVISSSPTHTDPIIRELLHRIRQSS...,MET31,Q03081,0.0,1.634189,1.205059,1.086330,0.203169
934,A_tiles_Q03081:112,HEKVHSLVLPHICSNCGKGFARKDALKRHSNTLTCQRNRKKLSEGS...,MET31,Q03081,112.0,0.944931,-0.138978,0.946555,-0.134766
935,A_tiles_Q03081:12,FLKQAAEAIAVISSSPTHTDPIIRELLHRIRQSSPLSAVIPAPENV...,MET31,Q03081,12.0,1.239286,0.526377,0.982992,-0.042090
936,A_tiles_Q03081:124,CSNCGKGFARKDALKRHSNTLTCQRNRKKLSEGSDVDVDELIKDAI...,MET31,Q03081,124.0,1.349659,0.735707,1.017686,0.043014
937,A_tiles_Q03081:25,SSPTHTDPIIRELLHRIRQSSPLSAVIPAPENVLKAGEPENMARGL...,MET31,Q03081,25.0,0.886908,-0.294463,0.969460,-0.076101
938,A_tiles_Q03081:37,LLHRIRQSSPLSAVIPAPENVLKAGEPENMARGLIRIPETQTKRTG...,MET31,Q03081,37.0,0.780446,-0.608212,0.918277,-0.209183
939,A_tiles_Q03081:50,VIPAPENVLKAGEPENMARGLIRIPETQTKRTGGNNHSKEGAQLYS...,MET31,Q03081,50.0,0.965893,-0.085145,0.955331,-0.112122
940,A_tiles_Q03081:62,EPENMARGLIRIPETQTKRTGGNNHSKEGAQLYSCAKCQLKFSRSS...,MET31,Q03081,62.0,1.047388,0.113598,0.939427,-0.153312
941,A_tiles_Q03081:74,PETQTKRTGGNNHSKEGAQLYSCAKCQLKFSRSSDLRRHEKVHSLV...,MET31,Q03081,74.0,0.828778,-0.460786,0.962779,-0.093066
942,A_tiles_Q03081:87,SKEGAQLYSCAKCQLKFSRSSDLRRHEKVHSLVLPHICSNCGKGFA...,MET31,Q03081,87.0,1.019396,0.047133,0.952419,-0.119611
943,A_tiles_Q03081:99,CQLKFSRSSDLRRHEKVHSLVLPHICSNCGKGFARKDALKRHSNTL...,MET31,Q03081,99.0,0.875895,-0.325120,0.937711,-0.157797

In [19]:
test_TFs = paddle_test_set['protein'].dropna().unique()

In [20]:
paddle_ads_subset = paddle_ads[[n in test_TFs for n in paddle_ads['protein']]]

In [21]:
paddle_ADs_w_full_seqs = paddle_ads_subset.merge(paddle_full_seqs)

In [22]:
# Check that AD is in the full sequence
for i in paddle_ADs_w_full_seqs.index: 
    print(paddle_ADs_w_full_seqs.loc[i, 'sequence'] in paddle_ADs_w_full_seqs.loc[i, 'protein sequence'])

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

In [24]:
paddle_ADs_w_full_seqs_filtered = paddle_ADs_w_full_seqs.drop_duplicates(['protein', 'protein sequence'])

In [25]:
# Write to fasta file
with open('paddle_test_seqs.fasta', 'w+') as f: 
    for i in paddle_ADs_w_full_seqs_filtered.index:
        f.write(">" + paddle_ADs_w_full_seqs_filtered.loc[i, 'protein'] + "\n")
        f.write(paddle_ADs_w_full_seqs_filtered.loc[i, 'protein sequence'] + "\n")

In [26]:
# Write to file for parrot
with open('paddle_test_seqs.tsv', 'w+') as f: 
    for i in paddle_ADs_w_full_seqs_filtered.index:
        f.write(paddle_ADs_w_full_seqs_filtered.loc[i, 'protein'] + " ")
        f.write(paddle_ADs_w_full_seqs_filtered.loc[i, 'protein sequence'] + "\n")

In [15]:
paddle_ADs_w_full_seqs.to_csv('paddle_test_seqs.csv')

# These are mutants, not part of real TFs

In [10]:
# The issue: Sanjana did not remove the PADDLE test sequences from the test set
# But they could be good evaluation set
# Maybe save them separately, and if they really help we can use them?

mutants = pd.read_excel("screen_data.xlsx", sheet_name="53 aa mutants, see Fig 2,4,7")
mutants

,Unnamed: 0,protein sequence,protein,protein ID,position,activation,Z score,group,num cells,"num cells, bin 1","num cells, bin 2","num cells, bin 3","num cells, bin 4","num cells, bin 5","num cells, bin 6","num cells, bin 7","num cells, bin 8",GFP average,GFP std
0,D_ADbest-AA-muts_P07248_415_DE,SENQPEFVEFQELLENETLGNELLETTAVLKEFELLHEESVSATAT...,ADR1,P07248,415.0,16.930617,4.545554,ADbest-AA-muts,39.106510,0.000000,0.000000,0.000000,4.211373,21.399212,13.495925,0.000000,0.000000,188.367987,1.952014
1,D_ADbest-AA-muts_P07248_415_ED,SDNQPDFVDFQDLLDNDTLGNDLLDTTAVLKDFDLLHDDSVSATAT...,ADR1,P07248,415.0,57.468119,6.509113,ADbest-AA-muts,138.026904,0.000000,0.000000,0.000000,2.105686,5.604555,60.249667,56.480461,13.586534,639.383311,2.009468
2,D_ADbest-AA-muts_P07248_648_DE,LPHFPIIHPSLLELELESLQRYTNEEGYEEAENAQLFERLSQGTEK...,ADR1,P07248,648.0,8.771608,3.488982,ADbest-AA-muts,53.525191,0.000000,0.732549,0.829402,17.371912,33.627333,0.963995,0.000000,0.000000,97.591841,1.969207
3,D_ADbest-AA-muts_P07248_648_ED,LPHFPIIHPSLLDLDLDSLQRYTNDDGYDDADNAQLFDRLSQGTDK...,ADR1,P07248,648.0,18.596741,4.696363,ADbest-AA-muts,163.682464,0.000000,1.098823,4.147011,14.213383,67.254665,73.263595,3.704986,0.000000,206.905080,2.367087
4,D_ADbest-AA-muts_P07269_0_DE,MMEEFSYEHEFNTHFATELEYLQHEQQQQQQQQHEQQHNQQQQPQP...,PHO2,P07269,0.0,9.113962,3.550498,ADbest-AA-muts,57.209762,0.000000,0.000000,1.658804,16.319069,39.231888,0.000000,0.000000,0.000000,101.400833,1.816528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2967,D_random_A50,YNPNYDTLSISSTCAVRKGNSLECSKEYFTDHELNYMSLEPRVERG...,NaN,NaN,NaN,0.979863,-0.032684,random,171.892454,14.631311,52.377247,102.845875,0.000000,2.038020,0.000000,0.000000,0.000000,10.901840,1.930767
2968,D_random_A6,QCADIDNPRRFLIRSLKDNSKNAYPKDVTKLFRRVYMIPFFGTSKS...,NaN,NaN,NaN,0.672308,-0.637923,random,94.403832,21.110120,38.458818,34.834893,0.000000,0.000000,0.000000,0.000000,0.000000,7.480012,2.025611
2969,D_random_A7,GFSWKLGDINAMKTAAVHCESGKLPDPSKLVALLLLSRLSNKEAIK...,NaN,NaN,NaN,0.767581,-0.424991,random,177.272960,22.243912,84.609400,68.840384,1.579265,0.000000,0.000000,0.000000,0.000000,8.540012,1.890185
2970,D_random_A8,RAAYNSASALDCWTEAPSIRVRAPEMYPGCGGTATAQSQMIQDVVK...,NaN,NaN,NaN,1.220634,0.320329,random,281.753232,0.000000,100.359201,152.610009,23.688971,5.095050,0.000000,0.000000,0.000000,13.580627,1.927087
2971,D_random_A9,FDVAPSQSQSRRTLISRDTPDPAREIAIQPLSNNFQVDTYETRMTR...,NaN,NaN,NaN,0.965291,-0.056757,random,297.429908,18.680567,128.928609,127.727942,21.583285,0.509505,0.000000,0.000000,0.000000,10.739716,1.995546

In [11]:
short_mutants = pd.read_excel("screen_data.xlsx", sheet_name="cAD muts and 9mers, see Fig 3,4")
short_mutants

,Unnamed: 0,protein sequence,protein,protein ID,position,activation,Z score,group,num cells,"num cells, bin 1","num cells, bin 2","num cells, bin 3","num cells, bin 4","num cells, bin 5","num cells, bin 6","num cells, bin 7","num cells, bin 8",GFP average,GFP std
0,E_AD-tiling_P07269_431,ASAVGQQGNIAPPFLNTNSSASATQSQSNT,PHO2,P07269,431.0,0.832057,-0.285877,AD-tiling,209.791941,23.863614,76.551361,106.992886,0.526422,0.000000,1.445992,0.411665,0.0,9.865234,2.084967
1,E_AD-tiling_P07269_432,ASAVGQQGIAPPFLNTNSSATSATQSQSNT,PHO2,P07269,432.0,1.038268,0.058393,AD-tiling,106.275372,3.617335,38.458818,54.740547,8.949167,0.509505,0.000000,0.000000,0.0,12.310166,1.947702
2,E_AD-tiling_P07269_433,ASAVGQQGAPPFLNTNSSATDSATQSQSNT,PHO2,P07269,433.0,1.194556,0.276423,AD-tiling,72.164278,0.000000,21.976467,45.617122,2.105686,1.019010,1.445992,0.000000,0.0,14.163181,2.071480
3,E_AD-tiling_P07269_434,ASAVGQQGPPFLNTNSSATDSSATQSQSNT,PHO2,P07269,434.0,0.882606,-0.194171,AD-tiling,192.282691,10.959986,79.847832,96.210658,5.264216,0.000000,0.000000,0.000000,0.0,10.464567,1.820251
4,E_AD-tiling_P07269_435,ASAVGQQGPFLNTNSSATDSNSATQSQSNT,PHO2,P07269,435.0,0.929712,-0.113322,AD-tiling,154.808692,3.887286,68.859598,76.305004,4.737794,1.019010,0.000000,0.000000,0.0,11.023075,1.804647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3616,E_random_B50,DFNIRILTLITGSQRPSDITNFSLTLCLAK,NaN,NaN,NaN,1.048795,0.074079,random,3320.828096,64.194202,941.325354,2273.391487,36.849511,4.585545,0.481997,0.000000,0.0,12.434977,1.625380
3617,E_random_B6,IKIQKPISITKGVMSIYSSSGYLGWGEEPL,NaN,NaN,NaN,1.057142,0.086404,random,176.949070,0.000000,61.167834,109.481093,5.790637,0.509505,0.000000,0.000000,0.0,12.533938,1.651096
3618,E_random_B7,LIDLTTRVKPRYYNNALWNHHLQESESRSC,NaN,NaN,NaN,1.092272,0.137236,random,280.503454,0.000000,115.010179,144.315986,8.949167,12.228121,0.000000,0.000000,0.0,12.950457,2.050992
3619,E_random_B8,QPHPINVLFSACATYQYPPFIVLIELEMTF,NaN,NaN,NaN,0.917089,-0.134579,random,58.714622,0.000000,28.935682,28.199675,1.579265,0.000000,0.000000,0.000000,0.0,10.873411,1.648004
3620,E_random_B9,GYRRKLCGSREANGDGSDNLGLLLKLPART,NaN,NaN,NaN,0.929185,-0.114203,random,193.926520,0.000000,87.539595,105.334082,1.052843,0.000000,0.000000,0.000000,0.0,11.016833,1.568521

In [12]:
# These are regions of nuclear proteins that PADDLE predicted to activate
nuclear_proteins = pd.read_excel("screen_data.xlsx", sheet_name="Nuclear proteins, see Fig 7")
nuclear_proteins['protein'].value_counts()

protein
IFH1       10
REC8        9
TOM1        9
SPT6        9
BRN1        9
           ..
FPR3        1
BPL1        1
FCF2        1
YER156C     1
YGR067C     1
Name: count, Length: 1003, dtype: int64

In [13]:
nuclear_proteins[nuclear_proteins['protein'] == "IFH1"]

,Unnamed: 0,protein sequence,protein,protein ID,position,activation,Z score,group,nuclear confident,disorder fraction,...,"num cells, bin 1","num cells, bin 2","num cells, bin 3","num cells, bin 4","num cells, bin 5","num cells, bin 6","num cells, bin 7","num cells, bin 8",GFP average,GFP std
79,D_nuc-hits_P39520_974,LDEIHEILGKDENDLLSVGDINGYDAQEGHVIEDTDADILASLTAP...,IFH1,P39520,974,16.541658,4.508211,nuc-hits,True,0.184486,...,0.269950,9.889410,0.000000,12.634118,91.710907,75.191585,5.186981,0.0,184.040480,2.781049
138,D_nuc-hits_P39520_767,GNNGDELTLNELLNMSELEDDSPSHTDDMENNYNDAINSKSTNGHA...,IFH1,P39520,767,11.823617,3.968709,nuc-hits,True,0.675052,...,0.000000,0.000000,1.658804,30.006030,67.764171,21.689880,0.000000,0.0,131.548121,2.107811
209,D_nuc-hits_P39520_384,VEDAENKFLQNEYNQENGYDEEDDEEDEIMSDFDMPFYEDPKFANL...,IFH1,P39520,384,9.190757,3.563980,nuc-hits,True,0.712788,...,0.000000,10.988234,21.564458,71.593336,218.577663,28.919840,0.000000,0.0,102.255250,2.450577
245,D_nuc-hits_P39520_593,ELRALDSDSLDIGTELDDDYEDDDDDSSVTNVFIDIDDLDPDSFYF...,IFH1,P39520,593,8.111338,3.363246,nuc-hits,True,0.773585,...,0.000000,0.732549,9.952827,43.166570,47.383969,14.459920,0.000000,0.0,90.245758,2.496458
398,D_nuc-hits_P39520_404,EEDDEEDEIMSDFDMPFYEDPKFANLYYYGDGSEPKLSLSTSLPLM...,IFH1,P39520,404,5.183905,2.643920,nuc-hits,True,0.601677,...,0.000000,3.662745,33.176089,108.969268,69.802191,1.445992,0.000000,0.0,57.675498,2.245373
566,D_nuc-hits_P39520_948,DASLIPHNSDLAVDSNTRKNSTKSVGLDEIHEILGKDENDLLSVGD...,IFH1,P39520,948,3.647137,2.078978,nuc-hits,True,0.490566,...,0.000000,4.395293,39.811307,124.761916,17.323171,0.000000,0.000000,0.0,40.577604,1.928911
648,D_nuc-hits_P39520_319,YDIDQDAYFDVINNEDSHGEIGTDLETGEDDLPILEEEEQNIVSEL...,IFH1,P39520,319,3.114517,1.825330,nuc-hits,True,0.798742,...,0.000000,0.000000,38.981904,66.329120,5.095050,0.000000,0.000000,0.0,34.651734,1.830463
654,D_nuc-hits_P39520_615,DDDDSSVTNVFIDIDDLDPDSFYFHYDSDGSSSLISSNSDKENSDG...,IFH1,P39520,615,3.090675,1.812984,nuc-hits,True,0.681342,...,0.000000,7.691764,5.805816,45.272256,1.019010,0.000000,0.000000,0.0,34.386479,2.054432
688,D_nuc-hits_P39520_1031,SNSMWRRRQSMVEAAAENLRFTKNGLFSESALADIEGIMGNDVNHS...,IFH1,P39520,1031,2.845360,1.680110,nuc-hits,True,0.232704,...,0.377931,4.761568,50.593535,56.327110,11.718616,0.000000,0.000000,0.0,31.657133,2.170229
974,D_nuc-hits_P39520_344,ETGEDDLPILEEEEQNIVSELQNDDELSFDGSIHEEGSDPVEDAEN...,IFH1,P39520,344,1.867764,1.003773,nuc-hits,True,0.857442,...,0.000000,1.098823,51.422938,16.319069,0.000000,0.000000,0.000000,0.0,20.780515,1.620089