In [1]:
import pandas as pd
import protfasta

In [2]:
train_seqs_dict = protfasta.read_fasta("data/train_seqs_with_test_overlap_removed.fasta")
train_seqs_df = pd.DataFrame({"id" : train_seqs_dict.keys(), "seq" : train_seqs_dict.values()})
train_seqs_df

,id,seq
0,Q8GGH0,MESFLLSKVSFVIKKIRLEKGMTQEDLAYKSNLDRTYISGIERNSR...
1,F1R2J1,MHEETSNSTLQGKTSFSIADILDPAKFNGTRETREISNNRESPKTT...
2,O75364,MEFGLLSEAEARSPALSLSDAGTPHPQLPEHGCKGQEHSDSEKASA...
3,P09087,MQQHHLQQQQQQQQQQEQQHLQEQQQHLQQLHHHAHHHLPQPLHTT...
4,Q05917,MEEGGRSPREEAAEPQESGGDAEPGGGRRALLLPPGDPPHPHPHPH...
...,...,...
232792,g004716.m1_yHMPu5000040912_saturnispora_halmia...,MQQKRAFPSNEGPNGDVNENQHGETIIANQETDRRGGMERDSEEAL...
232793,g002397.m1_yHMPu5000041691_saccharomycopsis_cr...,MSKRPGEETEEDTIKKLKIESQQPKDDNNVIDSELLTHQTNYQDDG...
232794,g002544.m1_yHDO593_barnettozyma_sp_180604.final,MDNISTPNQMEEQYTYLEEPAIIIDQNGGESQGLLTEQQQQQQQQL...
232795,g003106.m1_yHMPu5000034601_starmera_dryadoides...,QQQQQQQQQQQQQQQQQQPPPPPPPQQQVSESPNDPQPVQEVAVVE...
232796,g002629.m1_yHMPu5000034636_ogataea_nitratoaver...,MDHNSLPPQQTSANGIGYTYNEIDAYQDDINQYSQPQYSTQHQHQI...

In [3]:
# Can remove claire's sequences because predictors already ran

In [4]:
cl_seqs = protfasta.read_fasta("data/cl_seqs.fasta", invalid_sequence_action='remove')
cl_seqs_df = pd.DataFrame({"id": cl_seqs.keys(), "seq": cl_seqs.values()})
cl_seqs_df

,id,seq
0,g002981.m1_ashbya_aceri.final,MNRSDELQDAEDSGQQRYETYSCSRCRRLKKRCSKELPRCFSCEAA...
1,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...
2,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...
3,g000106.m1_candida_albicans.final,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...
4,g001050.m1_candida_dubliniensis.final,MRPTDSIVSKFRVQKPTSNLANNPAVLRHPENMPKLTSCLRCRKLK...
...,...,...
172849,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...
172850,g000938.m1_yHMPu5000040961_kazachstania_turice...,MQHHNMELDNLFDLDADIDFETAYQLFSNLDNIQEKNIDIFTQNVH...
172851,g003697.m1_yHMPu5000040963_lachancea_quebecuen...,MDTDRLLDIFDFDLEIDFETAYEMINKEDQNAKHATERSLVENEVD...
172852,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...
172853,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...

In [5]:
non_cl_train_seqs = train_seqs_df[~train_seqs_df["seq"].isin(cl_seqs_df["seq"])]
non_cl_train_seqs

,id,seq
0,Q8GGH0,MESFLLSKVSFVIKKIRLEKGMTQEDLAYKSNLDRTYISGIERNSR...
1,F1R2J1,MHEETSNSTLQGKTSFSIADILDPAKFNGTRETREISNNRESPKTT...
2,O75364,MEFGLLSEAEARSPALSLSDAGTPHPQLPEHGCKGQEHSDSEKASA...
3,P09087,MQQHHLQQQQQQQQQQEQQHLQEQQQHLQQLHHHAHHHLPQPLHTT...
4,Q05917,MEEGGRSPREEAAEPQESGGDAEPGGGRRALLLPPGDPPHPHPHPH...
...,...,...
229866,Itr_sc000023.1_g00016.1,MENGAAGGGVNGFGFPDKETAAGAAAAAESFRPENNNIMMGRHVHH...
229867,Itr_sc000070.1_g00002.1,MLYRTQHHSFLNPFTFSLTPPPPPPSSAVSVQGMECALKSCVRPEM...
229868,Itr_sc000049.1_g00017.1,MASRLPKTAPKLERKYVEKNRRNHLKNLYKHLFSLLPPHLSQEGIA...
229869,Itr_sc000205.1_g00022.1,MEFDSNSTHVGPALQPFPMPTNYFKSEFDDVFHTDSKGYNFQDLHP...
229870,Itr_sc000785.1_g00007.1,MEMVEKKLKTDTEASPSQMVTGRRTHVSSAPPNCTAALNTVTPCAA...

In [6]:
protfasta.write_fasta(dict(zip(non_cl_train_seqs["id"], non_cl_train_seqs["seq"])), "data/train_seqs_with_test_overlap_removed_sk_only.fasta")

In [8]:
# ! mkdir ../data/non_cl_train_seqs_split

In [9]:
# df = your loaded dataframe with columns: id, seq
chunk_size = 1000
file_paths = []

for i in range(0, len(non_cl_train_seqs), chunk_size):
    chunk = non_cl_train_seqs.iloc[i:i + chunk_size]
    fasta_content = ""
    for _, row in chunk.iterrows():
        fasta_content += f">{row['id']}\n{row['seq']}\n"

    file_path = f"data/splits/non_cl_train_seqs_split/pt{i//chunk_size + 1}.fasta"
    with open(file_path, "w") as f:
        f.write(fasta_content)
    file_paths.append(file_path)