In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Overlap between sequence sets

In [2]:
with open('../cl_seqs_names.txt', 'r') as f:
    cl_seqs = f.readlines()

In [3]:
with open('../all_seq_names.txt', 'r') as f:
    all_seqs = f.readlines()

In [4]:
with open('../non_cl_seqs.txt', 'r') as f:
    non_cl_seqs = f.readlines()

In [5]:
with open('../all_names_w_synthetics.txt', 'r') as f:
    all_seqs_w_synthetics = f.readlines()

In [6]:
cl_seqs = [s.strip() for s in cl_seqs]
all_seqs = [s.strip() for s in all_seqs]
all_seqs_w_synthetics = [s.strip() for s in all_seqs_w_synthetics]
non_cl_seqs = [s.strip() for s in non_cl_seqs]

In [7]:
cl_and_non_cl_seqs = cl_seqs + non_cl_seqs

In [8]:
set(all_seqs).difference(cl_and_non_cl_seqs)

{'A0A1G4KK32',
 'A0A9P6VSM4',
 'A0AAN7WTS9',
 'I2H6Y2',
 'P07249',
 'P27705',
 'P39970',
 'P40573',
 'Q08182',
 'Q12224',
 'Q5A1E3',
 'Q5AL36',
 'Q6FXJ5'}

In [9]:
set(cl_and_non_cl_seqs).difference(all_seqs_w_synthetics)

{'g000628.m1_yHMPu5000035297_priceomyces_castillae_170307.final',
 'g000962.m1_yHMPu5000034868_Vanderwaltozyma_yarrowii_S33_SPADES.final',
 'g002887.m1_yHMPu5000034947_ambrosiozyma_philentoma_160519.final',
 'g002598.m1_yHMPu5000035660_priceomyces_haplophilus_160613.final',
 'g002057.m1_yHMPu5000035721_candida_asparagi_160519.final',
 'g000841.m1_yHMPu5000035252_yamadazyma_nakazawae_170307.final',
 'g005081.m1_yHMPu5000035666_nakaseomyces_bacillisporus_160613.final',
 'g003107.m1_yHMPu5000037239_wickerhamiella_brachini_210210.final',
 'g003750.m1_saccharomyces_cerevisiae.final',
 'g003562.m1_yHMPu5000038318_teunomyces_stri_170713.final',
 'g001481.m1_yHMPu5000034984_candida_sharkiensis_160519.final',
 'g004136.m1_yHMPu5000041797_saccharomycopsis_fermentans_201018.final',
 'g005314.m1_yHMPu5000035026_Candida_anneliseae_SPADES.final',
 'g005459.m1_yHMPu5000038382_candida_mesorugosa_170713.final',
 'g001290.m1_yHMPu5000037912_candida_dendronema_170912.final',
 'g004950.m1_yHMPu5000040919_candida_konsanensis_201018.final',
 'g006790.m1_yHMPu5000037878_Lipomyces_kononenkoae_SPADES.final',
 'g004858.m1_yHMPu5000035626_zygosaccharomyces_siamensis_190924.final',
 'g002406.m1_yHMPu5000035633_candida_hispaniensis_180604.final',
 'g000667.m1_yHMPu5000035244_candida_incommunis_160928.final',
 'g002488.m1_yHMPu5000034994_candida_neerlandica_190924.final',
 'g001665.m1_yHMPu5000038314_yamadazyma_mexicana_170713.final',
 'g017880.m1_yHMPu5000034630_Magnusiomyces_magnusii_S134_MASURCA.haplomerger2.final',
 'g008437.m1_yHMPu5000035267_wickerhamomyces_lynferdii_170307.final',
 'g003612.m1_yHMPu5000034864_zygosaccharomyces_lentus_170307.final',
 'g002432.m1_yHMPu5000038317_tortispora_sangerardonensis_170713.final',
 'g003999.m1_yHAB159_kazachstania_solicola_160519.haplomerger2.final',
 'g000725.m1_yHMPu5000041779_schwanniomyces_pseudopolymorphus_190924.final',
 'g001286.m1_yHMPu5000035005_lodderomyces_elongisporus_160519.haplomerger2.final',
 'g005838.m1_yHMPu5000026052_candida_buinensis_201018.final',
 'g002967.m1_yHMPu5000040930_candida_hsintzibuensis_201018.final',
 'g004110.m1_yHMPu5000035703_cyberlindnera_americana_160613.final',
 'g003727.m1_yHMPu5000035721_candida_asparagi_160519.final',
 'g002055.m1_yHMPu5000037921_ascoidea_asiatica_201018.final',
 'g005964.m1_yHMPu5000037229_kodamaea_neixiangensis_210210.final',
 'g002532.m1_yHMPu5000037879_Lipomyces_spencer-martinsiae_S172_SPADES.final',
 'g008350.m1_yHMPu5000037199_metschnikowia_leonuri_210210._SPADES.haplomerger2.final',
 'g005396.m1_yHMPu5000038033_yamadazyma_insecticola_170912.final',
 'g001080.m1_yHMPu5000034619_candida_ethanolica_170307.haplomerger2.final',
 'g005452.m1_yHMPu5000038388_candida_inconspicua_170713.final',
 'g004883.m1_yHMPu5000034655_botryozyma_nematodophila_190924.haplomerger2.final',
 'g002708.m1_yHMPu5000034720_candida_nivariensis_180604.final',
 'g000950.m1_yHMPu5000034574_sugiyamaella_smithiae_180604.final',
 'g001184.m1_yHMPu5000034631_martiniozyma_abiesophila_170307.haplomerger2.final',
 'g002297.m1_yHMPu5000035627_zygosaccharomyces_pseudobailii_201018.haplomerger2.final',
 'g001652.m1_saccharomyces_jurei.final',
 'g001330.m1_yHMPu5000034615_saturnispora_zaruensis_160519.final',
 'g002404.m1_yHMPu5000026090_wickerhamiella_nectarea_210210.final',
 'g002532.m1_yHMPu5000041783_saccharomycopsis_schoenii_170912.final',
 'g010949.m1_yHMPu5000038388_candida_inconspicua_170713.final',
 'g007004.m1_yHMPu5000034747_lipomyces_orientalis_170307.final',
 'g002198.m1_yHMPu5000041792_schwanniomyces_capriottii_170912.final',
 'g000254.m1_yHMPu5000035671_phaffomyces_antillensis_160613.final',
 'g002762.m1_yHMPu5000035040_ambrosiozyma_maleeae_160519.final',
 'g002796.m1_yHMPu5000035662_meyerozyma_caribbica_160613.final',
 'g001408.m1_yHMPu5000038349_candida_viswanathii_170713.haplomerger2.final',
 'g004138.m1_yHMPu5000041862_candida_golubevii_170307.final',
 'g000864.m1_yHMPu5000038059_Nadsonia_commutata_S169_SPADES.final',
 'g002922.m1_yHMPu5000037201_metschnikowia_rubicola_210210.final',
 'g004543.m1_yHMPu5000037256_cyberlindnera_galapagoensis_210210.final',
 'g002477.m1_yHMPu5000038333_ogataea_chonburiensis_170713.final',
 'g000132.m1_candida_orthopsilosis.final',
 'g004980.m1_yHMPu5000034596_candida_sp_160613.final',
 'g001905.m1_yHMPu5000040919_candida_konsanensis_201018.final',
 'g005483.m1_yHMPu5000038085_candida_sp_170912.final',
 'g001977.m1_kazachstania_naganishii.final',
 'g001763.m1_yHMPu5000038108_Candida_khao-thaluensis_SPADES.final',
 'g001873.m1_yHMPu5000037888_candida_quercuum_170210.final',
 'g001350.m1_yHMPu5000037854_scheffersomyces_insectosa_170912.final',
 'g001076.m1_yHMPu5000034961_hanseniaspora_lachancei_170307.haplomerger2.final',
 'g000169.m1_yHMPu5000037851_saturnispora_ahearnii_170912.final',
 'g001514.m1_yHMPu5000038390_candida_ezoensis_170713.final',
 'g003114.m1_yHAB150_kazachstania_exigua_160519.final',
 'g003127.m1_hansenula_polymorpha.final',
 'g004303.m1_kluyveromyces_aestuarii.final',
 'g000529.m1_brettanomyces_anomalus.final',
 'g001709.m1_yHMPu5000035681_candida_gotoi_160519.final',
 'g000379.m1_candida_infanticola.final',
 'g000649.m1_yHMPu5000037890_candida_pimensis_180604.haplomerger2.final',
 'g002801.m1_yHMPu5000035675_kregervanrija_fluxuum_160613.final',
 'g000988.m1_yHMPu5000037859_ogataea_nakhonphanomensis_170210.final',
 'g008368.m1_yHMPu5000035627_zygosaccharomyces_pseudobailii_201018.haplomerger2.final',
 'g003214.m1_yHMPu5000041809_metschnikowia_chrysoperlae_170307.haplomerger2.final',
 'g004744.m1_yHMPu5000035713_candida_chauliodes_160613.final',
 'g000085.m1_yHMPu5000034739_lipomyces_yarrowii_190924.final',
 'g000669.m1_yHMPu5000035033_candida_cretensis_160519.final',
 'g000826.m1_saprochaete_ingens.final',
 'g001085.m1_yHMPu5000037239_wickerhamiella_brachini_210210.final',
 'g002261.m1_yHMPu5000035678_trichomonascus_ciferrii_160519.final',
 'g000667.m1_yHMPu5000038350_candida_sanyaensis_180604.haplomerger2.final',
 'g001076.m1_yHQL142_Suhomyces_sp_nov_plate33_DISCOVAR.final',
 'g003031.m1_yHMPu5000038380_candida_loeiensis_170713.final',
 'g002852.m1_yHAB155_kazachstania_spencerorum_160519.final',
 'g003399.m1_yHMPu5000041779_schwanniomyces_pseudopolymorphus_190924.final',
 'g003833.m1_yHMPu5000037253_nematodospora_anomalae_210210.final',
 'g003578.m1_yHMPu5000038383_candida_middelhoveniana_170713.final',
 'g003398.m1_yHMPu5000034669_Blastobotrys_raffinofermentans_SPAdes.final',
 'g000999.m1_yHMPu5000034687_blastobotrys_chiropterorum_170307.final',
 'g000693.m1_yHMPu5000026208_pichia_pseudocactophila_170307.haplomerger2.final',
 'g004622.m1_yHMPu5000040912_saturnispora_halmiae_201018.final',
 'g004253.m1_yHAB161_kazachstania_sinensis_160519.final',
 'g003159.m1_yHMPu5000035659_saturnispora_dispora_160519.final',
 'g002362.m1_yHAB157_kazachstania_bulderi_160519.haplomerger2.final',
 'g000347.m1_yHMPu5000037915_candida_catenulata_190924.final',
 'g000521.m1_yHQL449_Kodamaea_sp_nov_plate33_PLATANUS.final',
 'g006748.m1_yHMPu5000034759_lipomyces_kockii_170307.final',
 'g001925.m1_yHAB150_kazachstania_exigua_160519.final',
 'g002857.m1_yHMPu5000034675_blastobotrys_mokoenaii_160519.final',
 'g002534.m1_yHMPu5000035294_candida_fermenticarens_170307.final',
 'g004407.m1_yHMPu5000041800_ogataea_thermomethanolica_180604.final',
 'g003584.m1_hanseniaspora_uvarum.final',
 'g000324.m1_yHMPu5000035663_Meyerozyma_guilliermondii_MASURCA.final',
 'g000385.m1_yHMPu5000041804_metschnikowia_vanudenii_190924.final',
 'g001272.m1_yHMPu5000041859_candida_friederichii_160928.final',
 'g000062.m1_yHMPu5000038069_diutina_neorugosa_170912.final',
 'g003895.m1_yHMPu5000034918_nakazawaea_holstii_160519.final',
 'g002457.m1_yHMPu5000037834_zygosaccharomyces_parabailii_190924.haplomerger2.final',
 'g003993.m1_yHMPu5000035664_candida_carpophila_160613.final',
 'g003921.m1_yHMPu5000037226_ogataea_haglerorum_210305.final',
 'g004286.m1_yHMPu5000038098_candida_oceani_170912.final',
 'g005871.m1_yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES.final',
 'g001780.m1_saccharomyces_arboricola.final',
 'g003362.m1_yHMPu5000034719_candida_pseudohumilis_180604.haplomerger2.final',
 'g005387.m1_yHMPu5000041733_saccharomycopsis_javanensis_170912.final',
 'g002670.m1_yHMPu5000035319_Candida_tartarivorans_S177_SPADES.final',
 'g000008.m1_yHMPu5000026208_pichia_pseudocactophila_170307.haplomerger2.final',
 'g001497.m1_yHMPu5000035700_cyberlindnera_japonica_160519.final',
 'g005476.m1_yHMPu5000038036_yamadazyma_dushanensis_170912.final',
 'g001390.m1_yHMPu5000034589_wickerhamiella_australiensis_180604.final',
 'g001072.m1_yHMPu5000034642_candida_zeylanoides_160519.final',
 'g001572.m1_yHMPu5000034871_naumovozyma_castellii_180604.final',
 'g002416.m1_yHMPu5000035251_candida_aaseri_170307.final',
 'g011217.m1_yHMPu5000035269_wickerhamomyces_ciferrii_170307.final',
 'g001995.m1_yHMPu5000037208_metschnikowia_baotianmanensis_210210.final',
 'g005721.m1_yHMPu5000035648_yarrowia_porcina_170307.final',
 'g004694.m1_yHDO587_citeromyces_nyonsensis_180604.haplomerger2.final',
 'g003967.m1_yHMPu5000037229_kodamaea_neixiangensis_210210.final',
 'g003820.m1_yHMPu5000038090_candida_pseudocylindracea_210210.final',
 'g002196.m1_yHMPu5000038030_yamadazyma_phyllophila_170912.final',
 'g005162.m1_yHMPu5000038364_Candida_qinlingensis_SPADES.final',
 'g000604.m1_yHMPu5000034897_Ogataea_glucozyma_SPAdes.final',
 'g001999.m1_yHMPu5000034982_candida_ubatubensis_160519.final',
 'g002465.m1_yHMPu5000035323_diddensiella_santjacobensis_190924.final',
 'YPR009W_saccharomyces_cerevisiae.sgd',
 'g005477.m1_yHMPu5000037224_candida_vulturna_210210.final',
 'g002015.m1_yHMPu5000038322_schwanniomyces_polymorphus_var_africanus_170713.final',
 'g004421.m1_yHMPu5000034612_saturnispora_saitoi_180604.final',
 'g005066.m1_yHMPu5000034908_candida_sp_160519.final',
 'g004963.m1_yHMPu5000038121_candida_hungchunana_170912.final',
 'g000813.m1_yHMPu5000034586_candida_geochares_180604.final',
 'g001703.m1_yHAB152_candida_humilis_160519.haplomerger2.final',
 'g002812.m1_yHMPu5000035714_candida_frijolesensis_160519.haplomerger2.final',
 'g002951.m1_candida_parapsilosis.final',
 'g004491.m1_yHMPu5000034712_kluyveromyces_lactis_var_lactis_160519.final',
 'g001194.m1_yHMPu5000038349_candida_viswanathii_170713.haplomerger2.final',
 'g002597.m1_yHMPu5000037915_candida_catenulata_190924.final',
 'g002161.m1_saccharomyces_jurei.final',
 'g005602.m1_yHMPu5000034886_ogataea_trehalophila_160519.final',
 'g005158.m1_yHMPu5000038036_yamadazyma_dushanensis_170912.final',
 'g000814.m1_yHMPu5000026219_lachancea_waltii_180604.final',
 'g000836.m1_yHAB157_kazachstania_bulderi_160519.haplomerger2.final',
 'g004683.m1_yHMPu5000026150_trichomonascus_petasosporus_180604.final',
 'g002669.m1_yHMPu5000034626_pichia_kluyveri_170307.haplomerger2.final',
 'g002066.m1_yHKB15_Yamadazyma_sp_nov_plate33_SPADES.final',
 'g002501.m1_yHMPu5000040914_millerozyma_miso_201018.final',
 'g003439.m1_yHMPu5000038318_teunomyces_stri_170713.final',
 'g004542.m1_yHMPu5000035687_cyberlindnera_suaveolens_160613.final',
 'g001823.m1_yHMPu5000034877_tetrapisispora_namnaonensis_160519.final',
 'g006372.m1_yHMPu5000041773_sugiyamaella_castrensis_190924.final',
 'g003209.m1_yHMPu5000026055_diutina_siamensis_170912.final',
 'g008695.m1_yHMPu5000035269_wickerhamomyces_ciferrii_170307.final',
 'g004769.m1_yHMPu5000034655_botryozyma_nematodophila_190924.haplomerger2.final',
 'g005307.m1_yHMPu5000037852_scheffersomyces_cryptocercus_180604.final',
 'g005404.m1_yHMPu5000040943_metschnikowia_continentalis_201018.final',
 'g010825.m1_yHQL14_Wickerhamomyces_sp_nov_plate33_MASURCA.final',
 'g003923.m1_yHMPu5000035017_candida_bribrorum_160519.final',
 'g002180.m1_yHMPu5000034954_candida_norvegica_201018.final',
 'g004343.m1_yHMPu5000035268_wickerhamomyces_hampshirensis_160928.final',
 'g004752.m1_yHMPu5000041833_candida_tammaniensis_170307.final',
 'g000341.m1_yHDO566_kazachstania_ichnusensis_180604.final',
 'g005252.m1_yHMPu5000034920_nakazawaea_laoshanensis_170713.final',
 'g001984.m1_yHMPu5000035009_candida_terraborum_160519.final',
 'g002895.m1_yHMPu5000034575_sugiyamaella_paludigena_180604.final',
 'g005631.m1_yHKS617_Sugiyamaella_sp_nov_plate33_SPADES.final',
 'g004380.m1_yHMPu5000041691_saccharomycopsis_crataegensis_180604.final',
 'g001497.m1_yHMPu5000040921_candida_lessepsii_201018.final',
 'g004964.m1_yHMPu5000035687_cyberlindnera_suaveolens_160613.final',
 'g000174.m1_yHMPu5000034695_lachancea_fermentati_201018.final',
 'g006966.m1_yHMPu5000037923_ascoidea_tarda_180604.final',
 'g000928.m1_saprochaete_suaveolens.final',
 'g002604.m1_yHMPu5000034749_lipomyces_mesembrius_160519.final',
 'g002868.m1_yHMPu5000035035_candida_atbi_160519.final',
 'g005552.m1_yHMPu5000035718_Candida_tetrigidarum_SPADES.haplomerger2.final',
 'g006243.m1_yHMPu5000026279_Ambrosiozyma_monospora_SPADES.final',
 'g005719.m1_yHMPu5000041771_sugiyamaella_japonica_190924.final',
 'g005440.m1_yHMPu5000035009_candida_terraborum_160519.final',
 'g004085.m1_yHMPu5000035336_cyberlindnera_jadinii_180604.haplomerger2.final',
 'g003866.m1_yHMPu5000038050_saccharomycopsis_olivae_170912.final',
 'g001202.m1_yHMPu5000034639_candida_cariosilignicola_160519.final',
 'g004803.m1_kluyveromyces_aestuarii.final',
 'g002970.m1_yHMPu5000038377_candida_kutaonensis_170713.final',
 'g000607.m1_yHMPu5000037895_candida_jaroonii_180604.final',
 'g002965.m1_yHMPu5000038058_nakazawaea_siamensis_170912.final',
 'g000621.m1_yHMPu5000038381_candida_manassasensis_170713.final',
 'g001110.m1_komagataella_phaffi.final',
 'g005178.m1_yHMPu5000038068_cyberlindnera_samutprakarnensis_170912.haplomerger2.final',
 'g003611.m1_yHMPu5000038079_Candida_tanticharoeniae_SPADES.final',
 'g000524.m1_yHMPu5000026052_candida_buinensis_201018.final',
 'g002408.m1_yHMPu5000035668_nakazawaea_populi_160613.final',
 'g001342.m1_yHMPu5000034620_pichia_sp_170307.final',
 'g005255.m1_yHMPu5000034720_candida_nivariensis_180604.final',
 'g005525.m1_yHMPu5000041863_candida_gorgasii_160928.final',
 'g002968.m1_yHMPu5000035650_trigonopsis_variabilis_160613.final',
 'g001256.m1_yHMPu5000034668_blastobotrys_robertii_160519.final',
 'g001474.m1_yHMPu5000037906_candida_glucosophila_180604.final',
 'g001657.m1_yHMPu5000037873_debaryomyces_udenii_180604.final',
 'g005250.m1_yHMPu5000038038_saturnispora_quitensis_170912.final',
 'g005284.m1_yHMPu5000038386_candida_jianshihensis_170713.haplomerger2.final',
 'g007153.m1_yHMPu5000041772_sugiyamaella_chiloensis_170912.final',
 'g000223.m1_yHMPu5000038088_candida_potachaoreniae_180604.final',
 'g000646.m1_yHMPu5000037844_schwanniomyces_vanrijiae_var_vanrijiae_180604.final',
 'g001738.m1_yHMPu5000038069_diutina_neorugosa_170912.final',
 'g003208.m1_yHMPu5000034887_ogataea_trehaloabstinens_160519.final',
 'g003928.m1_yHMPu5000026137_ambrosiozyma_ambrosiae_160519.final',
 'g003957.m1_yHMPu5000041779_schwanniomyces_pseudopolymorphus_190924.final',
 'g003094.m1_yHMPu5000034863_zygosaccharomyces_rouxii_180604.final',
 'g000384.m1_yHMPu5000038329_metschnikowia_koreensis_180604.haplomerger2.final',
 'g002883.m1_yHMH580_Suhomyces_sp_nov_plate33_SPADES.final',
 'g001906.m1_metschnikowia_hawaiiensis.final',
 'g001892.m1_yHMPu5000034946_ambrosiozyma_oregonensis_160519.final',
 'g001450.m1_yHMPu5000034647_candida_savonica_180604.final',
 'g004847.m1_yHMPu5000034643_Candida_schatavii_SPAdes.final',
 'g002844.m1_yHMPu5000035248_candida_cerambycidarum_160928.final',
 'g001969.m1_metschnikowia_arizonensis.final',
 'g002434.m1_yHMPu5000037231_lipomyces_yamanashiensis_210210.final',
 'g000825.m1_yHMPu5000035300_pichia_sp_170307.final',
 'g004041.m1_yHMPu5000034886_ogataea_trehalophila_160519.final',
 'g000591.m1_yHMPu5000037847_pichia_cephalocereana_201018.final',
 'g002358.m1_yHMPu5000035652_torulaspora_maleeae_160613.final',
 'g002136.m1_yHMPu5000034613_saturnispora_serradocipensis_180604.final',
 'g003297.m1_yHMPu5000034633_candida_smithsonii_180604.final',
 'g005067.m1_yHMPu5000034752_dipodascopsis_uninucleata_var_uninucleata_170713.final',
 'g002134.m1_yHMPu5000038068_cyberlindnera_samutprakarnensis_170912.haplomerger2.final',
 'g001607.m1_yHMPu5000041796_saccharomycopsis_fibulgera_180604.haplomerger2.final',
 'g004033.m1_yHMPu5000040955_metschnikowia_bowlesiae_201018.final',
 'g004070.m1_yHMPu5000035044_barnettozyma_californica_160519.final',
 'g000455.m1_yHMPu5000034997_candida_tropicalis_160519.haplomerger2.final',
 'g000765.m1_yHMPu5000037844_schwanniomyces_vanrijiae_var_vanrijiae_180604.final',
 'g001823.m1_yHMPu5000034978_cyberlindnera_mrakii_160519.final',
 'g003370.m1_yHDO586_kazachstania_humatica_180604.final',
 'g005909.m1_yHMPu5000038385_candida_namnaoensis_170713.final',
 'g000872.m1_yHMPu5000034711_kluyveromyces_lactis_var_drosophilarum_160519.final',
 'g002837.m1_yHMPu5000034759_lipomyces_kockii_170307.final',
 'g001889.m1_yHMPu5000034615_saturnispora_zaruensis_160519.final',
 'g005569.m1_yHMPu5000035642_yamadazyma_triangularis_170307.final',
 'g000019.m1_yHMPu5000035697_hanseniaspora_thailandica_160519.haplomerger2.final',
 'g001521.m1_yHMH617_Wickerhamomyces_sp_nov_plate34_PLATANUS.final',
 'g003013.m1_yHMPu5000035687_cyberlindnera_suaveolens_160613.final',
 'g002224.m1_yHMPu5000034871_naumovozyma_castellii_180604.final',
 'g006366.m1_yHMPu5000041776_spencermartinsiella_ligniputridi_170912.final',
 'g002621.m1_yHMPu5000034592_metschnikowia_bicuspidata_var_bicuspidata_180604.final',
 'g004493.m1_yHDO572_zygosaccharomyces_mellis_180604.final',
 'g001121.m1_yHMPu5000034748_lipomyces_oligophaga_160519.final',
 'g005082.m1_yHMPu5000038087_candida_phayaonensis_170912.final',
 'g003481.m1_yHMPu5000038382_candida_mesorugosa_170713.final',
 'g001885.m1_yHMPu5000035644_yarrowia_deformans_180604.final',
 'g004885.m1_yHMPu5000037202_metschnikowia_peoriensis_210210.final',
 'g000170.m1_yHMPu5000038070_diutina_ranongensis_170912.final',
 'g001695.m1_yHAB142_kazachstania_gamospora_170307.haplomerger2.final',
 'g000983.m1_spathaspora_xylofermentans.final',
 'g004724.m1_yHMPu5000037865_metschnikowia_reukaufii_180604.haplomerger2.final',
 'g000535.m1_yHKS641_Suhomyces_sp_nov_plate33_SPADES.final',
 'g000806.m1_yHMPu5000035322_Diddensiella_transvaalensis_SPADES.final',
 'g003470.m1_yHMPu5000036579_candida_xyloterini_170912.final',
 'g001065.m1_komagataella_phaffi.final',
 'g001860.m1_yHMPu5000037853_scheffersomyces_illinoinensis_170912.final',
 'g002289.m1_yHMPu5000035246_candida_insectorum_160928.final',
 'g002668.m1_yHMPu5000035679_candida_rhagii_160613.final',
 'g004495.m1_ogataea_parapolymorpha.final',
 'g004128.m1_yHAB133_kazachstania_unispora_160519.final',
 'g004272.m1_yHQL494_Lachancea_sp_nov_plate34_PLATANUS.final',
 'g005038.m1_yHMPu5000040954_metschnikowia_cerradonensis_201018.final',
 'g000126.m1_spathaspora_hagerdaliae.final',
 'g003655.m1_yHMPu5000035316_candida_homilentoma_180604.final',
 'g004208.m1_yHMPu5000034720_candida_nivariensis_180604.final',
 'g001702.m1_yHMPu5000035030_Candida_lycoperdinae__SPADES.final',
 'g003484.m1_yHMPu5000040953_metschnikowia_kipukae_201018.final',
 'g002862.m1_yHMPu5000041792_schwanniomyces_capriottii_170912.final',
 'g003669.m1_yHKS641_Suhomyces_sp_nov_plate33_SPADES.final',
 'g001881.m1_yHMPu5000034744_lipomyces_spencer-martinsiae_170307.final',
 'g005048.m1_saccharomyces_kudriavzevii.final',
 'g002491.m1_yHMPu5000038097_candida_sp_201018.final',
 'g001199.m1_yHMPu5000040947_metschnikowia_gruessii_201018.final',
 'g004165.m1_yHMPu5000035626_zygosaccharomyces_siamensis_190924.final',
 'g000451.m1_candida_orthopsilosis.final',
 'g002573.m1_yHKS699_Yamadazyma_sp_nov_plate33_SPADES.final',
 'g002145.m1_yHMPu5000035022_candida_emberorum_160519.final',
 'g005275.m1_yHMPu5000038091_candida_pseudolambica_201018.final',
 'g001725.m1_yHMPu5000037202_metschnikowia_peoriensis_210210.final',
 'g005219.m1_yHMPu5000040913_pichia_manshurica_201018.final',
 'g004397.m1_yHMPu5000035639_wickerhamomyces_canadensis_160613.final',
 'g003418.m1_yHMPu5000041800_ogataea_thermomethanolica_180604.final',
 'g005160.m1_yHMPu5000035020_Candida_chickasaworum_SPADES.final',

In [10]:
len(cl_and_non_cl_seqs)

310001

In [11]:
len(set(cl_and_non_cl_seqs))

310001

In [12]:
len(set(cl_seqs))

172854

In [13]:
len(cl_seqs)

172854

In [14]:
len(set(all_seqs))

230302

In [15]:
len(all_seqs)

230302

In [16]:
len(set(cl_seqs).intersection(all_seqs))

95634

In [17]:
len(set(cl_seqs).difference(all_seqs))

77220

In [18]:
len(non_cl_seqs)

137147

In [19]:
len(set(non_cl_seqs))

137147

In [20]:
len(set(non_cl_seqs).intersection(all_seqs))

134655

In [21]:
len(set(non_cl_seqs).difference(all_seqs))

2492

In [22]:
sum(['Q8GGH0' in s for s in all_seqs])

1

In [23]:
sum(['Jcr4S03466.20' in s for s in all_seqs])

0

In [24]:
! grep 'Jcr4S03466.20' /global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/consensus_AD_predictor/data/train_seqs_with_test_synthetics_overlap_removed.fasta

In [25]:
! grep 'Q8GGH0' /global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/consensus_AD_predictor/data/train_seqs_with_test_synthetics_overlap_removed.fasta

>Q8GGH0

In [26]:
# set(non_cl_seqs).difference(all_seqs)

In [27]:
non_cl_seqs_to_keep = set(non_cl_seqs).intersection(all_seqs)
with open('../non_cl_seqs_filtered.txt', 'w+') as f:
    for name in non_cl_seqs_to_keep:
        f.write(name + "\n")

In [28]:
len(non_cl_seqs_to_keep)

134655

In [29]:
cl_seqs_to_keep = set(cl_seqs).intersection(all_seqs)
with open('../cl_seqs_filtered.txt', 'w+') as f:
    for name in cl_seqs_to_keep:
        f.write(name + "\n")

In [30]:
len(cl_seqs_to_keep)

95634

In [31]:
other_seqs = set(all_seqs).difference(cl_and_non_cl_seqs)
with open('../missing_seqs.txt', 'w+') as f:
    for name in other_seqs:
        f.write(name + "\n")

In [32]:
len(other_seqs)

13

In [33]:
with open('/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/consensus_AD_predictor/data/non_cl_train_seqs_split/pt1.fasta', 'r') as f:
    lines = f.readlines()

names = []
seqs = []
seq = ""

for line in lines:
    if line.startswith(">"):
        names.append(line.replace(">","").strip())
        if len(names) > 1:
            seqs.append(seq)
            seq = ""
    else:
        seq += line.strip()

seqs.append(seq)

seq_df = pd.DataFrame({'name' : names, 'seq' : seqs})
seq_df

       name                                                seq
0    Q8GGH0  MESFLLSKVSFVIKKIRLEKGMTQEDLAYKSNLDRTYISGIERNSR...
1    F1R2J1  MHEETSNSTLQGKTSFSIADILDPAKFNGTRETREISNNRESPKTT...
2    O75364  MEFGLLSEAEARSPALSLSDAGTPHPQLPEHGCKGQEHSDSEKASA...
3    P09087  MQQHHLQQQQQQQQQQEQQHLQEQQQHLQQLHHHAHHHLPQPLHTT...
4    Q05917  MEEGGRSPREEAAEPQESGGDAEPGGGRRALLLPPGDPPHPHPHPH...
..      ...                                                ...
995  A1XDT5  MGRGRVELKRIENKINRQVTFAKRRSGLFKKAHELSVLCDAEVALV...
996  A3QQT1  MGRGRVQLKRIENKINRQVTFSKRRMGLLKKAHEISVLCDAEVALI...
997  E2FEP5  IIFSSRGKLYEFSSSGNMNRTLERYQRSSYNTQDSSFAAPDRETQS...
998  K7R212  RRNGIFKKAEELTVLCDAKVSIIMFSNSGKCHEYISPSITTKQVYD...
999  K9LW01  MVRGKTQMKRIENETSRQVTFSKRRSGLLKKALELSVLCDAEVGLI...

[1000 rows x 2 columns]

In [34]:
preds = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/pt1_combined_no_composition.csv', index_col=0)
preds

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals
0,Q8GGH0,MESFLLSKVSFVIKKIRLEKGMTQEDLAYKSNLDRTYISGIERNSR...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[40465.336,39714.215,36622.324,39168.64,34978....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.1825367,0.18771008,0.1811311,0.16013218,0.1...","[0.014501843,0.017827885,0.00781931,0.01072559...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.017282724,-0.017990192,-0.021199908,-0.021...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.4579984247684479,-0.6400120854377747,-0.65...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
1,F1R2J1,MHEETSNSTLQGKTSFSIADILDPAKFNGTRETREISNNRESPKTT...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32509.066,30355.93,28649.129,25147.93,20923.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.1996398,0.1909486,0.19241591,0.19613661,0.1...","[0.0001438626,0.00035412342,0.0003735048,0.000...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.31806868,0.28675005,0.27596197,0.25877306,0...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.8958371877670288,-0.8978611826896667,-0.96...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(142, 182)]",NaN,NaN,NaN,NaN
2,O75364,MEFGLLSEAEARSPALSLSDAGTPHPQLPEHGCKGQEHSDSEKASA...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[29600.562,27908.555,23943.48,22679.992,21695....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.20011021,0.18792471,0.17850415,0.17156768,0...","[0.004338817,0.0073712594,0.008403782,0.016222...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.24082585,0.21805342,0.19448315,0.16699585,0...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.5172410011291504,-0.683373212814331,-0.757...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
3,P09087,MQQHHLQQQQQQQQQQEQQHLQEQQQHLQQLHHHAHHHLPQPLHTT...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[24640.102,24443.316,23884.91,23502.457,33014....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16546656,0.16327353,0.16205797,0.16644616,0...","[2.5173225e-05,1.9513469e-05,2.0737218e-05,1.6...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.418225,0.4298997,0.441755,0.44852835,0.4521...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.8030082583427429,-0.9208729863166809,-0.91...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(253, 300)]",NaN,NaN,NaN,NaN
4,Q05917,MEEGGRSPREEAAEPQESGGDAEPGGGRRALLLPPGDPPHPHPHPH...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[16339.532,15863.892,15742.899,16619.082,16961...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16999598,0.16993652,0.16276489,0.159435,0.1...","[0.00013295647,0.0001215624,0.00011178966,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.22651581,0.23068734,0.2278125,0.23869318,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.6571060419082642,-0.6609328985214233,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(133, 173)]",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A1XDT5,MGRGRVELKRIENKINRQVTFAKRRSGLFKKAHELSVLCDAEVALV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[51413.934,41891.56,31299.406,34105.49,47731.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.14698431,0.15077686,0.15947826,0.1671099,0....","[9.920816e-05,7.893124e-05,4.5066252e-05,3.543...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.048006438,-0.04692002,-0.04540624,-0.04514...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.144260972738266,-0.09302634000778198,-0.03...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
996,A3QQT1,MGRGRVQLKRIENKINRQVTFSKRRMGLLKKAHEISVLCDAEVALI...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[49317.914,38081.098,28271.762,31498.617,44360...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15026222,0.15196691,0.15868698,0.16502213,0...","[5.754361e-05,4.4599765e-05,2.405228e-05,1.650...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.06294079,-0.0628287,-0.06320184,-0.0638218...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.2731199562549591,-0.18780158460140228,-0.1...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
997,E2FEP5,IIFSSRGKLYEFSSSGNMNRTLERYQRSSYNTQDSSFAAPDRETQS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[30880.125,29675.223,29987.762,27137.082,26946...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18073903,0.19299541,0.16276014,0.15263793,0...","[0.005978944,0.005133317,0.006191265,0.0072129...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.3740685,0.35247514,0.37067327,0.37761226,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.5942774415016174,-0.491030752658844,-0.647...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(11, 51)]",NaN,NaN,NaN
998,K7R212,RRNGIFKKAEELTVLCDAKVSIIMFSNSGKCHEYISPSITTKQVYD...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[31795.426,36728.266,34868.48,27059.176,30833....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.1740086,0.17393337,0.16802591,0.16569468,0....","[0.0004033987,0.0007538197,0.0015578431,0.0012...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.04153533,0.12748273,0.196676,0.27353165,0.3...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.09295855462551117,0.25681406259536743,0.164...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
999,K9LW01,MVRGKTQMKRIENETSRQVTFSKRRSGLLKKALELSVLCDAEVGLI...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[40540.414,33286.91,27338.781,29618.445,32252....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15318295,0.15791129,0.16711314,0.17408204,0...","[5.2790838e-05,3.949016e-05,2.6815607e-05,1.57...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.057273816,-0.05539934,-0.054163456,-0.0544...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.18981531262397766,-0.0945950299501419,-0.0...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN

# Combined preds vs. fasta file

In [35]:
all_combined_no_sanjana = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_composition_combined.csv', index_col=0)
all_combined_no_sanjana

KeyboardInterrupt:

In [ ]:
all_combined_all_six = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_all_six_combined.csv', index_col=0)
all_combined_all_six

In [ ]:
all_combined_no_adhunter_ensemble = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_ADhunterEnsemble_combined.csv', index_col=0)
all_combined_no_adhunterlite = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_ADhunterLite_combined.csv', index_col=0)
all_combined_no_paddle = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_paddle_combined.csv', index_col=0)
all_combined_no_adpred = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_adpred_combined.csv', index_col=0)
all_combined_no_tada = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_tada_combined.csv', index_col=0)

In [ ]:
# Save sets so that it runs faster
all_six_names_set = set(all_combined_all_six['name'])
all_seqs_set = set(all_seqs)
all_seqs_w_synthetics_set = set(all_seqs_w_synthetics)

In [ ]:
# There are sequences in the "Parts" that are not in the final set of sequences
len(all_six_names_set.difference(all_seqs_set))

In [ ]:
# There are sequences in the "Parts" that are not in the final set of sequences
# All of these sequences are in the w/ synthetics set!
len(all_six_names_set.difference(all_seqs_w_synthetics_set))

In [ ]:
len(all_seqs_set.difference(all_six_names_set))

In [ ]:
# This takes a while
all_combined_all_six[[n in all_seqs for n in all_combined_all_six['name']]].to_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_all_six_combined_filtered.csv')

In [ ]:
# This takes a while
all_combined_no_sanjana[[n in all_seqs for n in all_combined_all_six['name']]].to_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/non_cl_seqs_no_composition_combined_filtered.csv')

In [ ]:
all_combined_no_adhunter_ensemble[[n in all_seqs for n in all_combined_no_adhunter_ensemble['name']]].to_csv('../predictions/combined_preds/non_cl_seqs_no_ADhunterEnsemble_combined_filtered.csv')
all_combined_no_adhunterlite[[n in all_seqs for n in all_combined_no_adhunterlite['name']]].to_csv('../predictions/combined_preds/non_cl_seqs_no_ADhunterLite_combined_filtered.csv')
all_combined_no_paddle[[n in all_seqs for n in all_combined_no_paddle['name']]].to_csv('../predictions/combined_preds/non_cl_seqs_no_paddle_combined_filtered.csv')
all_combined_no_adpred[[n in all_seqs for n in all_combined_no_adpred['name']]].to_csv('../predictions/combined_preds/non_cl_seqs_no_adpred_combined_filtered.csv')
all_combined_no_tada[[n in all_seqs for n in all_combined_no_tada['name']]].to_csv('../predictions/combined_preds/non_cl_seqs_no_tada_combined_filtered.csv')

# Extra random stuff

In [28]:
import ast
all_combined_no_sanjana_filtered = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/combined_no_sanjana_filtered_python.csv', 
                                  index_col=0,
                                  converters={'combined_preds' : ast.literal_eval})
all_combined_no_sanjana_filtered

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals
0,Aco021664.1,MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[23948.734,34398.383,34643.266,30163.777,46331...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.20640308,0.2299711,0.23149782,0.22729242,0....","[0.000457561,0.0005376012,0.00062079023,0.0016...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.15613313,0.1687365,0.17277826,0.17923725,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7733858227729797,-0.8443028330802917,-0.80...","[[,0,.,0,1,8,5,1,2,7,5,0,0,4,4,4,6,5,0,6,5,,, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
1,Aco014880.1,MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[163864.33,166590.23,153676.1,149345.64,139923...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.617012,0.60880744,0.6142499,0.6240743,0.621...","[0.08309816,0.17942944,0.29228172,0.2683431,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[7.2677155,7.249478,7.1840224,7.1038427,7.0258...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.41324320435523987,0.2205643206834793,0.3367...","[[,0,.,0,5,0,6,8,2,2,2,8,0,5,8,5,7,6,5,8,4,,, ...","[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.8, 0.8, ...","[(0, 51)]","[(0, 53)]","[(7, 24)]","[(0, 66)]",NaN
2,Aco002151.1,MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[40901.55,39849.902,44446.395,46577.89,48848.3...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15860836,0.16032039,0.16562296,0.16951677,0...","[0.0013301629,0.001206241,0.0013138953,0.00109...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.052201796,-0.056321103,-0.05690101,-0.0570...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.5648762583732605,-0.554851233959198,-0.579...","[[,0,.,0,1,4,0,2,0,3,9,5,4,6,5,1,9,5,1,7,9,,, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
3,Aco018224.1,MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[52955.406,57674.707,60400.03,63605.56,59457.2...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.189424,0.18299682,0.17208093,0.16736288,0.1...","[0.0027180198,0.0023544286,0.0015037733,0.0013...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.034381293,-0.034525078,-0.033828054,-0.032...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.8527296781539917,-0.8746128082275391,-0.93...","[[,0,.,0,1,0,5,2,5,4,0,8,2,0,0,9,1,9,6,2,8,,, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(395, 436)]","[(207, 260), (381, 448)]",NaN,"[(194, 261), (369, 449)]",NaN
4,Aco005374.1,MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[21428.078,23407.145,33649.83,28168.95,34537.4...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.19193147,0.19046147,0.17961264,0.1756722,0....","[0.0016205282,0.0021502455,0.004893229,0.00514...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.31436068,0.3567606,0.38733268,0.38166854,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.958437442779541,-1.0686415433883667,-1.035...","[[,0,.,0,2,7,5,6,2,9,7,5,8,8,3,4,8,3,8,8,7,,, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Q1L604,MERQNGPVANCEVRIGDTNAFPFANSNRSHGLDQVAQVKILEANQQ...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[42824.598,47310.406,45304.836,42242.062,49439...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17582999,0.18409999,0.19033362,0.18730128,0...","[0.00021953057,0.00022142378,0.00039207918,0.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[1.4143094,1.4100709,1.3768183,1.3130834,1.290...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.16060161590576172,-0.3421540856361389,-0.5...","[[,0,.,0,1,3,6,7,8,2,6,7,5,9,8,1,5,2,1,6,,, ,0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(456, 516)]","[(307, 350), (447, 509)]",NaN,NaN,"[(454, 506)]"
996,Q2V0V6,MGRAPCCEKMGLKKGPWSSEEDQILISFIQQNGHGNWRALPKLAGL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[46363.434,43221.117,40501.332,59808.125,73736...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.26488924,0.2812774,0.2547481,0.2515382,0.25...","[0.00012279596,9.898732e-05,0.00041308193,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.018593693,0.01561908,0.01072543,0.006017387...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.25009289383888245,-0.2474326193332672,-0.2...","[[,0,.,0,2,5,1,4,5,7,1,3,2,3,9,9,0,8,2,2,,, ,0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(151, 233)]","[(147, 233)]","[(204, 230)]","[(138, 234)]","[(172, 227)]"
997,Q4H2X0,RPEVNAGSSEGHPLFVNSNCGIKFPFPFGGTGRRRNRTSFSQHQLF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[55876.367,45973.496,38530.24,46176.977,42763....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18245177,0.17727578,0.17009905,0.16590858,0...","[0.00044469372,0.00089056103,0.0011923852,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.24777976,0.25223148,0.27359214,0.2873551,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3565596640110016,-0.22058431804180145,-0.1...","[[,0,.,0,6,3,4,3,4,9,3,6,1,0,6,2,0,4,9,9,,, ,0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(21, 72)]",NaN,NaN,NaN,NaN
998,Q4TU81,MALEPHHVDPNFYKLGENEIEVTLDADQEADGAAEGGSFGDGSLNG...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[29528.43,25633.969,27518.305,23582.0,26031.66...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.2983341,0.29295546,0.30117765,0.30229473,0....","[0.0030587474,0.0041588596,0.007043223,0.00695...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[1.048122,1.1171399,1.1885368,1.2451117,1.2890...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.6355088949203491,-0.5695153474807739,-0.50...","[[,0,.,0,2,5,8,6,6,9,7,9,7,3,3,1,0,9,4,7,4,,, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
999,Q59HD6,LMGWMGKRVWGGGPSKALDFHAACSPPACALYPPQPPICRRSPVTS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[58976.598,55733.12,50588.695,48535.574,52384....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.1999851,0.17782508,0.17508432,0.17580275,0....","[0.0031886662,0.0012930824,0.0013439738,0.0019...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.18174306,0.17550977,0.16999562,0.16817683,0...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.40883415937423706,-0.5224279165267944,-0.4...","[[,0,.,0,1,5,7,9,6,8,8,8,6,1,9,6,6,1,3,3,,, ,0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(103, 143)]",NaN,NaN,NaN,NaN

In [29]:
# From Sanjana
all_combined_no_sanjana_filtered = all_combined_no_sanjana_filtered.reset_index(drop=True)
preds_df = all_combined_no_sanjana_filtered['combined_preds'].apply(pd.Series)

# Number 
preds_df

,0,1,2,3,4,5,6,7,8,9,...,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.8,0.8,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134650,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134651,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134652,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134653,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134654,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# This should be 1! Yay it is!
preds_df.max().max()

1.0

In [32]:
# # Join the new columns back to the original DataFrame (drop old combined_preds)
parrot_input = pd.concat([all_combined_no_sanjana_filtered[['name', 'sequence']], preds_df], axis=1)
parrot_input

,name,sequence,0,1,2,3,4,5,6,7,...,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441
0,Aco021664.1,MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aco014880.1,MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aco002151.1,MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aco018224.1,MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aco005374.1,MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134650,Q1L604,MERQNGPVANCEVRIGDTNAFPFANSNRSHGLDQVAQVKILEANQQ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134651,Q2V0V6,MGRAPCCEKMGLKKGPWSSEEDQILISFIQQNGHGNWRALPKLAGL...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134652,Q4H2X0,RPEVNAGSSEGHPLFVNSNCGIKFPFPFGGTGRRRNRTSFSQHQLF...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134653,Q4TU81,MALEPHHVDPNFYKLGENEIEVTLDADQEADGAAEGGSFGDGSLNG...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134654,Q59HD6,LMGWMGKRVWGGGPSKALDFHAACSPPACALYPPQPPICRRSPVTS...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# parrot_input.to_csv('../predictions/combined_preds/final_data/parrot_input_no_sanjana.tsv', sep='\t', index=False, header=False)

# Debugging consensus again

In [27]:
test = pd.read_csv('../predictions/consensus_testing.csv',
            index_col=0,
            converters={'combined_preds' : ast.literal_eval})

In [28]:
test2 = test['combined_preds'].apply(pd.Series)
test2

,0,1,2,3,4,5,6,7,8,9,...,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
test2.max().max()

1.0

In [31]:
test2 = pd.concat([test[['name', 'sequence']], test2], axis=1)

In [36]:
import matplotlib.pyplot as plt

AttributeError: module 'matplotlib' has no attribute 'get_data_path'

In [ ]:
plt.plot(test[test['name'] == 'A0A9E8Z3T4']['combined_preds'].values[0)