In [1]:
import numpy as np
import pandas as pd
import matplotlib

In [4]:
with open('../predictions/combined_preds/final_data/parrot_input_all_six.tsv', 'r') as f:
    lines = f.readlines()

lines = [line.split() for line in lines]

names = [line[0] for line in lines]
seq = [line[1] for line in lines]
preds = [line[2:] for line in lines]

preds = [[float(n) for n in pred] for pred in preds]

In [5]:
pred_df = pd.DataFrame({'name' : names, 'seq' : seq, 'preds' : preds})

In [7]:
# Are there duplicate sequences? 

pred_df['seq'].drop_duplicates()

0         MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...
1         MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...
2         MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...
3         MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...
4         MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...
                                ...
226902    MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...
226903    MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...
226904    MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...
226905    MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...
226906    MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...
Name: seq, Length: 226450, dtype: object

In [8]:
pred_df['seq']

0         MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...
1         MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...
2         MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...
3         MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...
4         MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...
                                ...
226902    MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...
226903    MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...
226904    MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...
226905    MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...
226906    MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...
Name: seq, Length: 226907, dtype: object

In [29]:
duplicated_seqs = pred_df['seq'].value_counts()[pred_df['seq'].value_counts() > 1].index
duplicated_df = pred_df[[s in duplicated_seqs for s in pred_df['seq']]]
duplicated_df

Empty DataFrame
Columns: [name, seq, preds]
Index: []

In [23]:
duplicated_df['name'].value_counts()

name
g000992.m1_yHMPu5000041860_candida_galacta_170912.final    2
g000749.m1_alloascoidea_hylecoeti.final                    2
g000551.m1_arxula_adeninivorans.final                      2
C7_00890C_A_candida_albicans.cgd                           2
g001552.m1_candida_parapsilosis.final                      2
                                                          ..
g004230.m1_lachancea_cidri.final                           2
g004978.m1_magnusiomyces_ingens.final                      2
g001427.m1_saccharomyces_jurei.final                       2
g001331.m1_saccharomyces_mikatae.final                     2
g001232.m1_saccharomyces_uvarum.final                      2
Name: count, Length: 457, dtype: int64

In [24]:
# Check if sanjana's input has duplicates

In [25]:
with open('/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/consensus_AD_predictor/output/parrot_input_test_synthetics_removed.tsv', 'r') as f:
    lines = f.readlines()

lines = [line.split() for line in lines]

names = [line[0] for line in lines]
seq = [line[1] for line in lines]
preds = [line[2:] for line in lines]

preds = [[float(n) for n in pred] for pred in preds]

In [27]:
pred_df = pd.DataFrame({'name' : names, 'seq' : seq, 'preds' : preds})
pred_df

,name,seq,preds
0,Q8GGH0,MESFLLSKVSFVIKKIRLEKGMTQEDLAYKSNLDRTYISGIERNSR...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,F1R2J1,MHEETSNSTLQGKTSFSIADILDPAKFNGTRETREISNNRESPKTT...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,O75364,MEFGLLSEAEARSPALSLSDAGTPHPQLPEHGCKGQEHSDSEKASA...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,P09087,MQQHHLQQQQQQQQQQEQQHLQEQQQHLQQLHHHAHHHLPQPLHTT...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,Q05917,MEEGGRSPREEAAEPQESGGDAEPGGGRRALLLPPGDPPHPHPHPH...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...
230297,g004716.m1_yHMPu5000040912_saturnispora_halmia...,MQQKRAFPSNEGPNGDVNENQHGETIIANQETDRRGGMERDSEEAL...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
230298,g002397.m1_yHMPu5000041691_saccharomycopsis_cr...,MSKRPGEETEEDTIKKLKIESQQPKDDNNVIDSELLTHQTNYQDDG...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
230299,g002544.m1_yHDO593_barnettozyma_sp_180604.final,MDNISTPNQMEEQYTYLEEPAIIIDQNGGESQGLLTEQQQQQQQQL...,"[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, ..."
230300,g003106.m1_yHMPu5000034601_starmera_dryadoides...,QQQQQQQQQQQQQQQQQQPPPPPPPQQQVSESPNDPQPVQEVAVVE...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
230301,g002629.m1_yHMPu5000034636_ogataea_nitratoaver...,MDHNSLPPQQTSANGIGYTYNEIDAYQDDINQYSQPQYSTQHQHQI...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [30]:
pred_df['max_pred'] = [max(ls) for ls in pred_df['preds']]

In [31]:
pred_df['max_pred'].value_counts()

max_pred
0.8    60858
0.6    53911
0.0    46489
0.4    34501
0.2    32946
1.0     1597
Name: count, dtype: int64

In [28]:
pred_df['seq'].drop_duplicates()

0         MESFLLSKVSFVIKKIRLEKGMTQEDLAYKSNLDRTYISGIERNSR...
1         MHEETSNSTLQGKTSFSIADILDPAKFNGTRETREISNNRESPKTT...
2         MEFGLLSEAEARSPALSLSDAGTPHPQLPEHGCKGQEHSDSEKASA...
3         MQQHHLQQQQQQQQQQEQQHLQEQQQHLQQLHHHAHHHLPQPLHTT...
4         MEEGGRSPREEAAEPQESGGDAEPGGGRRALLLPPGDPPHPHPHPH...
                                ...
230297    MQQKRAFPSNEGPNGDVNENQHGETIIANQETDRRGGMERDSEEAL...
230298    MSKRPGEETEEDTIKKLKIESQQPKDDNNVIDSELLTHQTNYQDDG...
230299    MDNISTPNQMEEQYTYLEEPAIIIDQNGGESQGLLTEQQQQQQQQL...
230300    QQQQQQQQQQQQQQQQQQPPPPPPPQQQVSESPNDPQPVQEVAVVE...
230301    MDHNSLPPQQTSANGIGYTYNEIDAYQDDINQYSQPQYSTQHQHQI...
Name: seq, Length: 230302, dtype: object

In [36]:
pd.read_csv('/global/scratch/users/claireleblanc/transcription_factors/Mbf1/Mbf1_orthologs_consensus_all_six.csv')

,Unnamed: 0,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,adhunter_ensemble_intervals
0,0,g002206.m1_alloascoidea_hylecoeti.final,MSNQDWDSVTIIGSRAKVGGGGPRATVAKSNSAINTARRSGNVVAV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[31678.324,30557.746,26648.953,34134.055,41683...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16389889,0.16854826,0.17358078,0.18004979,0...","[0.006507894,0.006102503,0.0036927424,0.005204...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.059342384,0.032025736,0.004040105,-0.020319...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.0673828125,-1.0407660007476807,-1.14047789...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
1,1,g002589.m1_arxula_adeninivorans.final,MADQDWDSVTVIGSRARVGGGGPRATVARTQAEINAAKRSGNVLAV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[33583.523,28920.2,26760.004,29370.91,35841.79...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.163534,0.16563995,0.1716504,0.18100405,0.17...","[0.008879358,0.008539465,0.005566197,0.0070098...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.14988956,0.11622739,0.07913082,0.04689637,0...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.0170416831970215,-0.9209909439086914,-0.92...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
2,2,g001201.m1_ashbya_aceri.final,MSSDWDTNTVIGQRVRTGGGGPRQQVARTQGQINAARRAGLVLSVD...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38717.61,36937.504,47802.66,58367.76,64075.11...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16534293,0.1722093,0.18035229,0.1728626,0.1...","[0.0046831267,0.0032712112,0.0027260326,0.0031...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.018226862,-0.039970238,-0.060295243,-0.074...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.0375592708587646,-1.0328490734100342,-1.04...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
3,3,g001157.m1_brettanomyces_anomalus.final,MSDWDNVTVIGRKAKRGSSGPREKVVRSSGALNAARRQGAVTAVEK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[40921.586,41813.65,41277.516,52233.33,59443.4...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17183162,0.18095683,0.17514278,0.16918118,0...","[0.0024475444,0.0013047968,0.0013743541,0.0011...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.06634717,-0.07228001,-0.07681342,-0.080064...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.8899303674697876,-0.8777462244033813,-0.91...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
4,4,C1_01060W_A_candida_albicans.cgd,MSSDWDSVTIIGQKARVGGGGPRENVAKTSSQLNAARRAGLVVGTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38572.53,38618.47,44911.637,53687.617,54155.7...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17002344,0.17562,0.18433069,0.1781372,0.167...","[0.0065741763,0.004673411,0.005111733,0.006011...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[0.012619972,-0.020653844,-0.047775507,-0.0672...","[27,28,29,30,31,32,33,34]","[-0.9311639666557312,-0.9227076768875122,-1.00...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172,1172,g000846.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MSDWDSTTVIGQRVRTGGGGPKQQVARTQGQINAARRSGNVLSVDK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26685.758,32376.98,40479.914,50889.65,52438.4...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17006817,0.17453903,0.16690826,0.16004951,0...","[0.0037507194,0.002876902,0.0033146194,0.00444...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.018427085,-0.046570938,-0.06618129,-0.0801...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.075002670288086,-1.1268973350524902,-1.136...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
1173,1173,g002415.m1_yHQL527_Metschnikowia_sp_nov_plate3...,MSDDWDSVTIIGQRARVGGGGPRQNVTKTAGQLNAARRTGAVINTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[42466.39,50092.29,54296.22,51417.344,50601.55...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16855898,0.17213045,0.18125714,0.17523418,0...","[0.012722942,0.009844306,0.011863697,0.0115122...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.07240443,0.03108263,-0.0034973621,-0.029020...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.021864652633667,-0.8477765917778015,-0.964...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
1174,1174,g002484.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MSDWDSVTVIGQKARIGGGGPRQNVAKTQSQLNAARRSGNVVGTEK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[25144.547,28887.379,40776.27,39155.96,39265.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17342311,0.18117791,0.17265421,0.16340601,0...","[0.0037345313,0.0050016386,0.005587662,0.00668...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.010132599,-0.03966256,-0.060192723,-0.0739...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.0604358911514282,-1.0548536777496338,-1.07...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
1175,1175,g001151.m1_yarrowia_lipolytica.final,MSDDWESKTVIGSRARVGGGGPRATVAKTQAEINAAMRSGNVLSTD...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32418.785,27072.156,31780.836,38311.336,47488...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16449979,0.1688196,0.16249613,0.15778933,0....","[0.0024739867,0.0014533403,0.0020617063,0.0020...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.078023575,-0.09884449,-0.11273364,-0.12179...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.977473258972168,-1.0207104682922363,-1.047...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN
1176,1176,g002606.m1_zygosaccharomyces_bailii.final,MSDWDSTTIIGRRARAGGSGPRSQVARTQGQVNEARRTGAVLSVDK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[46068.996,51082.62,49152.543,53483.25,55017.7...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16732094,0.17335303,0.17165236,0.16830114,0...","[0.002857334,0.002472556,0.0030089142,0.003533...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.023247194,-0.0054070554,-0.026164839,-0.042...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.0293049812316895,-0.9641305804252625,-1.05...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN

In [41]:
names_df = pd.read_csv('/global/scratch/users/claireleblanc/transcription_factors/Mbf1/Mbf1_orthologs.csv', header=None)

In [37]:
import protfasta

In [38]:
preds = protfasta.read_fasta(f"/global/scratch/users/claireleblanc/transcription_factors/Mbf1/Mbf1_orthologs.fasta")
preds = pd.DataFrame({"name" : preds.keys(), "sequence" : preds.values()})
preds

,name,sequence
0,g002206.m1_alloascoidea_hylecoeti.final,MSNQDWDSVTIIGSRAKVGGGGPRATVAKSNSAINTARRSGNVVAV...
1,g002589.m1_arxula_adeninivorans.final,MADQDWDSVTVIGSRARVGGGGPRATVARTQAEINAAKRSGNVLAV...
2,g001201.m1_ashbya_aceri.final,MSSDWDTNTVIGQRVRTGGGGPRQQVARTQGQINAARRAGLVLSVD...
3,g001157.m1_brettanomyces_anomalus.final,MSDWDNVTVIGRKAKRGSSGPREKVVRSSGALNAARRQGAVTAVEK...
4,C1_01060W_A_candida_albicans.cgd,MSSDWDSVTIIGQKARVGGGGPRENVAKTSSQLNAARRAGLVVGTE...
...,...,...
1172,g000846.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MSDWDSTTVIGQRVRTGGGGPKQQVARTQGQINAARRSGNVLSVDK...
1173,g002415.m1_yHQL527_Metschnikowia_sp_nov_plate3...,MSDDWDSVTIIGQRARVGGGGPRQNVTKTAGQLNAARRTGAVINTE...
1174,g002484.m1_yHRVM31_Schwanniomyces_sp_nov_plate...,MSDWDSVTVIGQKARIGGGGPRQNVAKTQSQLNAARRSGNVVGTEK...
1175,g001151.m1_yarrowia_lipolytica.final,MSDDWESKTVIGSRARVGGGGPRATVAKTQAEINAAMRSGNVLSTD...
1176,g002606.m1_zygosaccharomyces_bailii.final,MSDWDSTTIIGRRARAGGSGPRSQVARTQGQVNEARRTGAVLSVDK...

In [46]:
names_df['joint_name'] = names_df[0] + "_" + names_df[1]

In [48]:
set(names_df['joint_name']).difference(preds['name'])

{'g000759.m1_Phanerochaete_chrysosporium.final',
 'g001139.m1_Cryptococcus_neoformans.final',
 'g002332.m1_Ustilago_maydis.final',
 'g002486.m1_xylona_heveae.final',
 'g002825.m1_schizosaccharomyces_pombe.final',
 'g002903.m1_Mixia_osmundae.final',
 'g003788.m1_Malassezia_globosa.final',
 'g004756.m1_Agaricus_bisporus.final',
 'g004848.m1_Coccidioides_immitis.final',
 'g005364.m1_stagonospora_nodorum.final',
 'g005547.m1_Saitoella_complicata.final',
 'g006537.m1_neurospora_crassa.final',
 'g007348.m1_arthrobotrys_oligospora.final',
 'g007635.m1_Microbotryum_violaceum.final',
 'g008387.m1_botrytis_cinerea.final',
 'g008639.m1_Scleroderma_citrinum.final',
 'g008681.m1_Puccinia_graminis.final',
 'g008777.m1_sclerotinia_sclerotiorum.final',
 'g008873.m1_aspergillus_nidulans.final',
 'g010943.m1_fusarium_graminearum.final',
 'g013015.m1_Postia_placenta.final'}