In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def read_fasta(file):
    with open(file, 'r') as f:
        lines = f.readlines()
    names = []
    seqs = []
    seq = ""
    for line in lines: 
        if line.startswith('>'): 
            names.append(line.replace(">", "").strip())
            if len(names) > 1:
                seqs.append(seq)
                seq = ""
        else:
            seq += line.strip()
    
    seqs.append(seq)

    return pd.DataFrame({'name' : names, 'sequence' : seqs})

In [3]:
TFs_for_test_set = ['THAP12', 'CEBPG', 'FOXJ2', 'HOXA2', 'NR3C2', 'NR2C1', 'PKNOX2',
       'THRA', 'ZBTB20', 'MAFG', 'MBD6', 'ELF3', 'TEAD1', 'ZSCAN23',
       'ZNF121', 'SOX1', 'ZNF532', 'CREB3', 'ZNF683', 'ZNF80', 'NFE2L3',
       'NFATC2', 'L3MBTL3', 'ATOH8', 'NR2F1']

In [4]:
ad_data = pd.read_excel('List_of_delrosso_ADs.xlsx')
all_data = pd.read_excel('delrosso_data.xlsx')

In [5]:
all_data_filtered = all_data[[s in TFs_for_test_set for s in all_data['HGNC Symbol']]] #["HGNC Symbol"].value_counts()

In [7]:
all_data_filtered[all_data_filtered['HGNC Symbol'] == 'CREB3']

,HGNC Symbol,Tile Number,Tile Start,Tile End,label,R1_minCMV,countsON_R1_minCMV,countsOFF_R1_minCMV,R2_minCMV,countsON_R2_minCMV,...,Avg_pEF_batchRetest,Standard Error_pEF_batchRetest,extended DNA Sequence,DNA Sequence,Protein Sequence,Ensembl ID,Hit PGK,Hit pEF,Hit minCMV,Hit FLAG
16061,CREB3,0,1,80,TFTiles;ENSG00000107175;CREB3;0;1;80;583,7.696213,160512.0,2287.0,7.847232,141587.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccGAGCTGGAACTCGATG...,GAGCTGGAACTCGATGCTGGAGACCAGGACCTCCTGGCCTTCCTGC...,ELELDAGDQDLLAFLLEESGDLGTAPDEAVRAPLDWALPLSEVPSD...,ENSG00000107175,Not Hit,NaN,Hit,Not Hit
16062,CREB3,1,11,90,TFTiles;ENSG00000107175;CREB3;1;11;90;583,7.267711,4537.0,87.0,7.366343,6452.0,...,-0.289968,0.161924,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTGCTGGCTTTCCTGC...,CTGCTGGCTTTCCTGCTCGAGGAAAGTGGCGATTTGGGGACAGCAC...,LLAFLLEESGDLGTAPDEAVRAPLDWALPLSEVPSDWEVDDLLCSL...,ENSG00000107175,Not Hit,Hit,Hit,Not Hit
16063,CREB3,2,21,100,TFTiles;ENSG00000107175;CREB3;2;21;100;583,-1.186890,77.0,518.0,-0.853369,101.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccGATTTGGGCACAGCAC...,GATTTGGGCACAGCACCCGACGAGGCCGTGAGGGCTCCACTGGACT...,DLGTAPDEAVRAPLDWALPLSEVPSDWEVDDLLCSLLSPPASLNIL...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16064,CREB3,3,31,110,TFTiles;ENSG00000107175;CREB3;3;31;110;583,3.386752,446.0,126.0,0.958739,76.0,...,-0.654824,0.114187,TCCaGACCGTTCaGGTGTGCGTCTCTctccAGGGCCCCACTGGACT...,AGGGCCCCACTGGACTGGGCACTGCCTCTTTCTGAAGTGCCTAGCG...,RAPLDWALPLSEVPSDWEVDDLLCSLLSPPASLNILSSSNPCLVHH...,ENSG00000107175,Not Hit,Hit,NaN,Hit
16065,CREB3,4,41,120,TFTiles;ENSG00000107175;CREB3;4;41;120;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccTCTGAGGTACCAAGCG...,TCTGAGGTACCAAGCGACTGGGAAGTGGACGATTTGCTGTGCTCCC...,SEVPSDWEVDDLLCSLLSPPASLNILSSSNPCLVHHDHTYSLPRET...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16066,CREB3,5,51,130,TFTiles;ENSG00000107175;CREB3;5;51;130;583,NaN,NaN,NaN,NaN,NaN,...,-0.619382,0.335314,TCCaGACCGTTCaGGTGTGCGTCTCTctccGATTTGCTGTGCTCCC...,GATTTGCTGTGCTCCCTGCTGAGTCCCCCCGCAAGCTTGAACATCC...,DLLCSLLSPPASLNILSSSNPCLVHHDHTYSLPRETVSMDLESESC...,ENSG00000107175,Hit,Hit,NaN,Hit
16067,CREB3,6,61,140,TFTiles;ENSG00000107175;CREB3;6;61;140;583,3.633521,21.0,5.0,NaN,NaN,...,-0.873962,0.383587,TCCaGACCGTTCaGGTGTGCGTCTCTctccGCTAGCTTGAATATAC...,GCTAGCTTGAATATACTCTCTTCATCCAACCCCTGCCTTGTCCACC...,ASLNILSSSNPCLVHHDHTYSLPRETVSMDLESESCRKEGTQMTPQ...,ENSG00000107175,Hit,Not Hit,NaN,NaN
16068,CREB3,7,71,150,TFTiles;ENSG00000107175;CREB3;7;71;150;583,NaN,NaN,NaN,NaN,NaN,...,-0.747364,0.106291,TCCaGACCGTTCaGGTGTGCGTCTCTctccCCCTGCCTTGTCCACC...,CCCTGCCTTGTCCACCATGACCACACCTACTCCCTCCCACGGGAAA...,PCLVHHDHTYSLPRETVSMDLESESCRKEGTQMTPQHMEELAEQEI...,ENSG00000107175,Hit,Not Hit,NaN,Hit
16069,CREB3,8,81,160,TFTiles;ENSG00000107175;CREB3;8;81;160;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccTCCCTGCCAAGAGAAA...,TCCCTGCCAAGAGAAACTGTCTCTATGGACCTCGAGAGTGAGAGCT...,SLPRETVSMDLESESCRKEGTQMTPQHMEELAEQEIARLVLTDEEK...,ENSG00000107175,Not Hit,NaN,NaN,NaN
16070,CREB3,9,91,170,TFTiles;ENSG00000107175;CREB3;9;91;170;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTGGAATCCGAGAGCT...,CTGGAATCCGAGAGCTGCAGAAAAGAGGGGACCCAGATGACTCCCC...,LESESCRKEGTQMTPQHMEELAEQEIARLVLTDEEKSLLEKEGLIL...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16071,CREB3,10,101,180,TFTiles;ENSG00000107175;CREB3;10;101;180;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccACCCAGATGACGCCAC...,ACCCAGATGACGCCACAGCACATGGAGGAACTGGCAGAACAGGAGA...,TQMTPQHMEELAEQEIARLVLTDEEKSLLEKEGLILPETLPLTKTE...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16072,CREB3,11,111,190,TFTiles;ENSG00000107175;CREB3;11;111;190;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTGGCAGAGCAGGAGA...,CTGGCAGAGCAGGAGATCGCCAGGCTCGTACTGACCGACGAAGAAA...,LAEQEIARLVLTDEEKSLLEKEGLILPETLPLTKTEEQILKRVRRK...,ENSG00000107175,NaN,NaN,NaN,NaN
16073,CREB3,12,121,200,TFTiles;ENSG00000107175;CREB3;12;121;200;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTGACGGACGAAGAGA...,CTGACGGACGAAGAGAAGAGTCTGTTGGAAAAGGAGGGACTGATCC...,LTDEEKSLLEKEGLILPETLPLTKTEEQILKRVRRKIRNKRSAQES...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16074,CREB3,13,131,210,TFTiles;ENSG00000107175;CREB3;13;131;210;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAAGGAGGGGCTTATAC...,AAGGAGGGGCTTATACTGCCCGAAACCCTGCCTCTCACTAAGACCG...,KEGLILPETLPLTKTEEQILKRVRRKIRNKRSAQESRRKKKVYVGG...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16075,CREB3,14,141,220,TFTiles;ENSG00000107175;CREB3;14;141;220;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCCCCTCACTAAGACAG...,CCCCTCACTAAGACAGAGGAACAAATACTGAAGCGCGTGCGGAGGA...,PLTKTEEQILKRVRRKIRNKRSAQESRRKKKVYVGGLESRVLKYTA...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16076,CREB3,15,151,230,TFTiles;ENSG00000107175;CREB3;15;151;230;583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAAACGCGTGCGGAGAA...,AAACGCGTGCGGAGAAAGATTCGAAATAAAAGATCTGCTCAAGAAT...,KRVRRKIRNKRSAQESRRKKKVYVGGLESRVLKYTAQNMELQNKVQ...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16077,CREB3,16,161,240,TFTiles;ENSG00000107175;CREB3;16;161;240;583,3.826166,24.0,5.0,NaN,NaN,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAGATCTGCTCAAGAAT...,AGATCTGCTCAAGAATCTCGCAGGAAAAAGAAGGTGTATGTTGGGG...,RSAQESRRKKKVYVGGLESRVLKYTAQNMELQNKVQLLEEQNLSLL...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16078,CREB3,17,171,250,TFTiles;ENSG00000107175;CREB3;17;171;250;583,3.996091,27.0,5.0,6.407997,229.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAAGGTGTATGTTGGGG...,AAGGTGTATGTTGGGGGCTTGGAAAGCAGAGTGCTGAAATACACCG...,KVYVGGLESRVLKYTAQNMELQNKVQLLEEQNLSLLDQLRKLQAMV...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16079,CREB3,18,181,260,TFTiles;ENSG00000107175;CREB3;18;181;260;583,9.085125,919.0,5.0,5.997452,201.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccGTCTTGAAATATACTG...,GTCTTGAAATATACTGCCCAGAATATGGAACTCCAAAACAAGGTAC...,VLKYTAQNMELQNKVQLLEEQNLSLLDQLRKLQAMVIEISNKTSSS...,ENSG00000107175,Not Hit,NaN,Hit,Not Hit
16080,CREB3,19,191,270,TFTiles;ENSG00000107175;CREB3;19;191;270;583,2.134548,159.0,107.0,2.066645,241.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTTCAGAACAAAGTTC...,CTTCAGAACAAAGTTCAGCTCCTGGAAGAACAGAATTTGTCCCTGT...,LQNKVQLLEEQNLSLLDQLRKLQAMVIEISNKTSSSSTCILVLLVS...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16081,CREB3,20,201,280,TFTiles;ENSG00000107175;CREB3;20;201;280;583,5.971216,276.0,13.0,5.839322,386.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCAGAATTTGTCCCTGT...,CAGAATTTGTCCCTGTTGGATCAACTGAGAAAACTCCAGGCAATGG...,QNLSLLDQLRKLQAMVIEISNKTSSSSTCILVLLVSFCLLLVPAMY...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16082,CREB3,21,211,290,TFTiles;ENSG00000107175;CREB3;21;211;290;583,2.195675,262.0,169.0,2.525503,383.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAAGCTCCAGGCGATGG...,AAGCTCCAGGCGATGGTGATTGAGATATCTAACAAAACCTCCAGCA...,KLQAMVIEISNKTSSSSTCILVLLVSFCLLLVPAMYSSDTRGSLPA...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16083,CREB3,22,221,300,TFTiles;ENSG00000107175;CREB3;22;221;300;583,-1.505707,133.0,1116.0,-2.533569,102.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAACAAGACTAGTTCCT...,AACAAGACTAGTTCCTCTAGCACCTGCATCTTGGTCCTGCTGGTGT...,NKTSSSSTCILVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLR...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16084,CREB3,23,231,310,TFTiles;ENSG00000107175;CREB3;23;231;310;583,-2.347706,219.0,3294.0,-1.219319,593.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccTTGGTCCTGCTTGTAA...,TTGGTCCTGCTTGTAAGTTTCTGCCTCCTGCTTGTGCCTGCGATGT...,LVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQL...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit
16085,CREB3,24,241,320,TFTiles;ENSG00000107175;CREB3;24;241;320;583,-0.347742,217.0,816.0,-0.323477,227.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTTGTTCCTGCTATGT...,CTTGTTCCTGCTATGTACTCCTCTGACACTAGGGGGAGCCTGCCAG...,LVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVP...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16086,CREB3,25,251,330,TFTiles;ENSG00000107175;CREB3;25;251;330;583,-0.365220,129.0,491.0,0.203975,190.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccAGGGGGAGCCTGCCAG...,AGGGGGAGCCTGCCAGCTGAACATGGAGTCTTGTCCCGGCAGCTTA...,RGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDG...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16087,CREB3,26,261,340,TFTiles;ENSG00000107175;CREB3;26;261;340;583,6.958045,70645.0,1679.0,6.616866,74991.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccTTGAGCCGGCAGCTTA...,TTGAGCCGGCAGCTTAGGGCCCTCCCCAGTGAGGACCCATACCAAC...,LSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGN...,ENSG00000107175,Not Hit,NaN,Hit,Hit
16088,CREB3,27,271,350,TFTiles;ENSG00000107175;CREB3;27;271;350;583,6.464238,50527.0,1691.0,5.969011,49438.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccGAGGACCCATATCAAC...,GAGGACCCATATCAACTGGAGCTGCCTGCCCTTCAGTCAGAAGTGC...,EDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGNTSCLLHYMPQ...,ENSG00000107175,Not Hit,NaN,Hit,Hit
16089,CREB3,28,281,360,TFTiles;ENSG00000107175;CREB3;28;281;360;583,4.204997,2172.0,348.0,5.603932,5749.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCTGCAGTCTGAAGTGC...,CTGCAGTCTGAAGTGCCGAAAGATAGCACCCACCAATGGTTGGATG...,LQSEVPKDSTHQWLDGSDCVLQAPGNTSCLLHYMPQAPSAEPPLEW...,ENSG00000107175,Not Hit,NaN,NaN,Hit
16090,CREB3,29,291,370,TFTiles;ENSG00000107175;CREB3;29;291;370;583,4.631540,3347.0,399.0,4.897822,3055.0,...,NaN,NaN,TCCaGACCGTTCaGGTGTGCGTCTCTctccCACCAGTGGTTGGACG...,CACCAGTGGTTGGACGGCTCCGATTGTGTGCTGCAGGCCCCGGGGA...,HQWLDGSDCVLQAPGNTSCLLHYMPQAPSAEPPLEWPFPDLFSEPL...,ENSG00000107175,Not Hit,NaN,NaN,Not Hit

In [6]:
ad_data_filtered = ad_data[[s in TFs_for_test_set for s in ad_data['HGNC symbol']]]
ad_data_filtered

,HGNC symbol,UniProt ID,Domain type,Domain,Start,End,Sequence,Max avg act,Length,Domain overlaps annotation
53,CREB3,O43889,AD,1,1,90,ELELDAGDQDLLAFLLEESGDLGTAPDEAVRAPLDWALPLSEVPSD...,2.958982,90,1
54,CREB3,O43889,AD,2,181,260,VLKYTAQNMELQNKVQLLEEQNLSLLDQLRKLQAMVIEISNKTSSS...,2.958982,80,0
55,CREB3,O43889,AD,3,261,350,LSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGN...,2.958982,90,0
79,ELF3,P78545,AD,1,1,90,AATCEISNIFSNYFSAMYSSEDSTLASVPPAATFGADDLVLTLSNP...,1.552915,90,0
80,ELF3,P78545,AD,2,111,190,LVFGPLGDQLHAQLRDLTSSSSDELSWIIELLEKDGMAFQEALDPG...,1.552915,80,1
81,ELF3,P78545,AD,3,131,210,SSDELSWIIELLEKDGMAFQEALDPGPFDQGSPFAQELLDDGQQAS...,1.552915,80,1
132,HOXA2,O43364,AD,1,291,375,PTVPNCLSTMGQNCGAGLNNDSPEALEVPSLQDFSVFSTDSCLQLS...,3.405876,90,0
209,NFATC2,Q13469,AD,1,1,100,NAPERQPQPDGGDAPGHEPGGSPQDELDFSILFDYEYLNPNEEEPN...,0.455087,100,1
219,NFE2L3,Q9Y4A8,AD,1,251,340,HLNGTDTSFSLEDLFQLLSSQPENSLEGISLGDIPLPGSISDGMNS...,1.848783,90,0
220,NFE2L3,Q9Y4A8,AD,2,311,450,DVNLHEAILLCPNNTFRRDPTARTSQSQEPFLQLNSHTTNPEQTLP...,1.848783,140,0
369,ZNF532,Q9HCE3,AD,1,1,80,TMGDMKTPDFDDLLAAFDIPDMVDPKAAIESGHDDHESHMKQNAHG...,0.450331,80,0

In [7]:
# These are the full sequences of the TFs of interest
lambert_TFs = read_fasta('lambert_TFs_10-21-24_with_DBD_coords.fasta')
lambert_TFs["UniProt ID"] = lambert_TFs["name"].str.split("|").str[1]
lambert_TFs = lambert_TFs.rename(columns={'sequence' : 'full_seq'})

In [8]:
# We need a way to translate the uniprot IDs to get out the TFs of interest
name_df = pd.read_table('lambert_tfs_gene_names.tsv')
uniprot_IDs_for_test_set = name_df[[n in TFs_for_test_set for n in name_df['Gene Names (primary)']]]['Entry'].values

uniprot_TFs_for_test_set = lambert_TFs[[n in uniprot_IDs_for_test_set for n in lambert_TFs['UniProt ID']]]

In [9]:
# Add ADs to test TFs that have ADs
test_TFs_w_ADs = uniprot_TFs_for_test_set.merge(ad_data_filtered, how='outer')

In [10]:
test_TFs_w_ADs.to_csv('delrosso_test_TFs_w_ADs.csv')

In [14]:
test_TFs_w_ADs_filtered = test_TFs_w_ADs.drop_duplicates(['UniProt ID', 'full_seq'])

In [15]:
with open('delrosso_test_TFs_w_ADs.fasta', 'w+') as f:
    for i in test_TFs_w_ADs_filtered.index:
        f.write(">" + test_TFs_w_ADs_filtered.loc[i, 'UniProt ID'] + "\n")
        f.write(test_TFs_w_ADs_filtered.loc[i, 'full_seq'] + "\n")

In [ ]:
with open('delrosso_test_TFs_w_ADs.tsv', 'w+') as f:
    for i in test_TFs_w_ADs_filtered.index:
        f.write(test_TFs_w_ADs_filtered.loc[i, 'UniProt ID'] + " ")
        f.write(test_TFs_w_ADs_filtered.loc[i, 'full_seq'] + "\n")